### ISSUE TITLE
[PROPOSAL] Replace EUI with AWS UI 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#1228]
**Is your feature request related to a problem? Please describe.**

Reading https://github.com/opensearch-project/OpenSearch-Dashboards/issues/695 it looks like EUI may not be the best path forward for OpenSearch Dashboards, or at least require a lot of work.

**Describe the solution you'd like**

Replace EUI with AWS UI. The latter is a "complete design system, includes [AWS UI](https://www.npmjs.com/package/@awsui/components-react)—a collection of more than 50 React components that help create intuitive, responsive, and accessible interfaces for web applications". For all we can criticize the AWS UX, it is a very rich set of components and is open-source and licensed under APLv2.

**Describe alternatives you've considered**

There are other UX packages and design system alternatives, I propose opening separate issues for any candidates.

**Additional context**

https://github.com/aws/awsui-documentation/blob/main/README.md
https://www.npmjs.com/package/@awsui/components-react

**Comment by kgcreative** [comment]
I think if we're going to propose replacing EUI we should explore other open-source frameworks in addition to AWS UI. 

From an early exploration of AWS UI (and as an internal user of the AWS Design system) - some of my initial concerns are information density, theme-ability, and how easy it would be for us to add components to the base system. 

Additionally, AWS UI was created with the intent of creating AWS-Console-like administration experiences, and OpenSearch Dashboards does not really fit that paradigm. 

Finally, while AWS UI provides a pretty comprehensive group of from editing and table components, it falls short when it comes to some of the application-like control and interaction primitives that we would need for Dashboards and visualizations.

I think I would need to see a component-by-component parity table in order to evaluate if the AWS-UI components fit our needs

**Comment by seanneumann** [comment]
Totally agree with you @kgcreative. 

I'd like to also add that while we on the AWS team are stewards of the project, we're committed to making sure that both OpenSearch and Dashboards are community focused and driven projects and not biased towards the needs of AWS. I feel bringing in a framework like "AWS UI" might cloud that effort. 

All this being said, we should be constantly thinking about how to evolve our user experiences and the tools that make them. Let's keep the conversation going.
