### ISSUE TITLE
Health check optimization (cluster.state)

### ISSUE THREAD

**Issue by johnnyon-amzn** [opensearch-project/OpenSearch-Dashboards#1354]
**Is your feature request related to a problem? Please describe.**
[Health check](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9a095a877ae8611b001ecee6d67cef371ba2debc/src/core/server/opensearch/version_check/ensure_opensearch_version.ts#L65) uses the entire cluster.state API to get domain instance numbers from nodes.

This will slow down OSD if customer clusters are large.

**Describe the solution you'd like**

Add the metric for nodes only for lighter payload

Additional context

**Comment by gkamat** [comment]
This issue can lead to severe degradation in tail latencies, especially in clusters where the cluster state is large, but not necessarily huge (70+ MB).  In one cluster with only 3 data nodes (but holding about 2500 shards), tail latencies degraded from under 500 ms to 6 seconds.  In this particular cluster, the workload was not particularly intense.  In fact, it was an ingestion of 1 doc/sec and no search traffic.  When one of the slow operations was profiled, it was found that the node performing the actual indexing finished the task in under 1 ms, however, network congestion due to the *_cluster/state* calls delayed requests and responses between the coordinator and indexing node.  Thus, the time reported for the operation by OpenSearch was ~2.5 seconds.

Given the tiny size of this cluster and the severity of the impact of the health check call observed, it is likely that in larger clusters with even a modest number of shards, there will be a perceptible or even substantial impact on tail latencies.  This has been confirmed in at least one other case as well where the cluster has only ~200 shards but a latency degradation of >10X.  Therefore, it will be helpful to expedite the resolution of this problem.

When OSD is turned off, there is a dramatic improvement in tail latency as can be seen in the graph attached.

![osd-disable](https://user-images.githubusercontent.com/3145033/158734301-322e064d-6832-4874-967a-acaa1e9bd38c.jpg)

**Comment by engechas** [comment]
This issue was observed on a 50 data node cluster. The overhead of the OSD health check resulted in a 12x average query latency degradation:

Average query latency with OSD enabled: 1112.12ms
Average query latency with OSD disabled: 90.75ms

Similar to the latency graph attached by @gkamat, the latencies on the 50 node cluster were inconsistent, either taking single-digit milliseconds or around 1 second depending on if the call overlapped with the OSD health check.

The API being called by the health check is `/_cluster/state`. This requires the entire state of the cluster to be transmitted from the master to the data node on each health check call. When the cluster state is large, this adds significant overhead to the cluster.

Based on the [health check](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9a095a877ae8611b001ecee6d67cef371ba2debc/src/core/server/opensearch/version_check/ensure_opensearch_version.ts#L65) code, it appears only the `nodes` sub-object of the cluster state is used. Switching the health check to query `/_cluster/state/nodes` should provide the same data needed for the health check without transmitting the rest of the cluster state data over the network.

**Comment by seraphjiang** [comment]
Thanks @kavilla
