### ISSUE TITLE
[UX] Redesigned Global Header

### ISSUE THREAD

**Issue by kgcreative** [opensearch-project/OpenSearch-Dashboards#1583]
# UX Changes:
- Consolidates the global header in order to minimize wasted space.
- Moves help and user contexts to the side bar
- Minimizes the OpenSearch Dashboards branding and removes the redundant 2nd header bar
- User context menu should be collapsed by default

### Header, Nav Closed - Before
![image](https://user-images.githubusercontent.com/3443142/168299117-3e09bef4-6a1f-4414-929f-a22a463bc04c.png)

### Header, Nav Closed - After
![image](https://user-images.githubusercontent.com/3443142/168304506-ef693bf5-197e-4c58-ad45-0c4282aac058.png)

### Header, Nav Open, Before & After

![image](https://user-images.githubusercontent.com/3443142/168313323-6e50c536-5702-4055-985a-98420d6d5041.png)

Related Issues:
- #569 
- #810 
- [OpenSearch Dashboards logo feels wrong](https://forum.opensearch.org/t/opensearch-dashboards-logo-feels-wrong/6510/15)

**Comment by joshuarrrr** [comment]
I'm going to re-summarize these changes as a series of actions/transformations (actions marked [Proposed] are ambiguous in the mocks, but my suggested solutions):

1. The logo (which links to home) on the top bar will be replaced with a mark that appears between the nav toggle button and the breadcrumb.
2. [Proposed] The loading spinner (which currently appears to the right of the logo) is combined with the placement of 1. (By default, or if a custom loading mark is configured, the mark itself will indicate the loading state. If there's a custom static mark, but no custom loading mark, the loading indicator will take the place of the mark during loading).
3. [Proposed] The existing navigational control sections we make available in the top bar (`navControlsCenter`, `observables.navControlsRight` will move to the lower bar, on either side of the `currentActionMenu`).
4. The help menu contents will be moved to the collapsible nav menu (it will no longer be a popover).
5. Update functional tests that are looking for header elements in the wrong places.

Note that the "user context" menu referenced in the requirements [comes from the security plugin](https://github.com/opensearch-project/security-dashboards-plugin/blob/59247fbb115d2e34033273e9a2d8788c8ea7bcc1/public/apps/account/account-app.tsx#L77-L93). But any other community or custom plugins can add navigation menu items in the same way. Changing the behavior of those UI elements from a popover menu directly accessible in a menu bar to an expandable list of menu items in the collapsible nave menu is a rather significant change, and one we should probably provide a bit more time for. (It would either require plugin owners to [rewrite their popover menus](https://github.com/opensearch-project/security-dashboards-plugin/blob/59247fbb115d2e34033273e9a2d8788c8ea7bcc1/public/apps/account/account-nav-button.tsx#L144-L158), or we'd have to write some sort of brittle conversion utility). So I suggest that we only move the help menu for now and allow the other nav items to remain on the consolidated bar (3). That will also reduce the likelihood of breaking plugin functional tests.

**Comment by kgcreative** [comment]
Thank you for the summary, joshuarrr. I'm ok with the proposed solutions.

Regarding item 3

> [Proposed] The existing navigational control sections we make available in the top bar (navControlsCenter, observables.navControlsRight will move to the lower bar, on either side of the currentActionMenu).

I would propose we  move those to the right of the brand icon, and left of the breadcrumbs. This would allow the `currentActionMenu` to stay flush right. I am open to input on this suggestion, however.

**Comment by kavilla** [comment]
Is this to target `2.0`? I believe it is correct. Perhaps we can over a "beta" version that is toggled in settings that enables to use the new header to prevent any "breaking" changes related to testing or automation.

**Comment by joshuarrrr** [comment]
@kgcreative Here's the labeled parts of the existing dual headers.

![localhost_5603_hmd_app_discover (1)](https://user-images.githubusercontent.com/1679762/168645831-36f513fc-dff4-46e9-9f26-c61fde35f751.png)

**Comment by kgcreative** [comment]
Given the new datapoints above, here is the redesigned header.

### Redesigned Header, Revised
![image](https://user-images.githubusercontent.com/3443142/168670910-dd65bb2f-d268-4f83-91ba-c909f01aaf85.png)

In summary:
I'm going to call the current sections: Top Header A, Top Header B, Top Header C; Bottom Section A, Bottom Section B, Bottom Section C.

New zone ordering in the combined header:
Bottom Section A | Top Header A | Bottom Section B | Top Header B -> Bottom Section C | Top Header C

This rearranges all the current sections into a single combined row. @joshuarrrr - let's look at how this stacks in the mobile views as well.

This means the current menu does not have any additional settings.
### Menu, Revised
![image](https://user-images.githubusercontent.com/3443142/168671509-4adf24f8-1b06-4256-8c8b-0b903f2d9dfa.png)

**Comment by kgcreative** [comment]
@ahopp -- the "Discover" section is intended to provide additional help for each section (in context) -- so if you are in "Observability" -- then that section should be labeled "observability" -- etc. We can take a pass at those in a later update. One of the things I want to propose in the future is a right-hand drawer that will provide contextual help anywhere you are. This might change how the "help" menu behaves in a pretty fundamental level.

**Comment by kgcreative** [comment]
@ahopp Re: Differentiation between drawer headers vs drawers content, that's on our todo list as we redesign our visual language.

**Comment by evamillan** [comment]
Thanks for considering how this affects the custom plugins that use the header sections. But not all of them just add a small icon button with a popover and may need more space. For example, the way to access the different dashboards is to open the side bar, click on “Dashboard” and browse through the list. This requires many clicks and is confusing to users who are not used to the platform, so in our company we developed a plugin that adds a menu on the top bar to organise them and help users navigate through them:

![headers](https://user-images.githubusercontent.com/26812577/169320088-5d8c6fa7-dbf8-4dea-9275-f8c8d09d4f1c.png)


With this proposal we would have significantly less space on the header and our menu would be confused with the action menu or the breadcrumbs. What would be the way to handle this case?

**Comment by kgcreative** [comment]
@evamillan - thank you so much for this additional data point! Looks like you've made great use of what we've been considering "Wasted space" in that top header bar to add a lot of value for your customers.

Without going down too far in to the "solutioning" rabbit hole, I can think of a couple approaches:

1. You could collapse the custom menu into some sort of "drawer" that can be accessed via a custom menu either before or after the action menu, perhaps with some sort of clear text label. The drawback here is that it would likely hurt discoverability, since it would hide a lot of those menu items behind yet another nav.
2. We might consider a "compressed" vs "extended" header. This would mean some sort of configuration that would allow you to set a flag to use the double header.

@evamillan  - do you have a preference in the approach?
@joshuarrrr - given the 2.0 release timeline, what's the feasibility of approach 2?

**Comment by kavilla** [comment]
Just an update from my understanding we will be targeting a non-breaking change for 2.1 for this.

**Comment by kgcreative** [comment]
@kavilla - Yes. I'd like to dive deeper into @evamillan's use case, as well as allow for additional time for community feedback for this change. I'm going to iterate the design a bit and look for a path to provide additional options

**Comment by evamillan** [comment]
@kgcreative I prefer the second approach over the first one. As you said, a collapsed menu would make navigation harder for users.

**Comment by kgcreative** [comment]
> @kgcreative I prefer the second approach over the first one. As you said, a collapsed menu would make navigation harder for users.

Thanks @evamillan! We're moving this out so we can properly account for your needs in a non-breaking way. We may still do some visual cleanup in how the stacked header works and rearrange things a bit. I'll iterate in the open so you can provide feedback.

**Comment by joshuarrrr** [comment]
While @kgcreative is working on accounting for these other use cases, I've put the PR into draft mode. But I wanted to at least share a demo of the current state we've gotten to so far:

![simplified-header](https://user-images.githubusercontent.com/1679762/170381736-746c8c12-f89f-4afd-9092-4a180b3cfd52.gif)

It's also worth noting that there's already an option [to load applications in a "chromeless" mode](https://github.com/elastic/kibana/pull/49795), where the global UI chrome (such as the global header) are hidden. If we opt for an optional second or otherwise extended menu, I'm kind of thinking it's an extension of this idea, that it's possible to have `0`, `1`, or `2` menu bars (I think it doesn't make much sense to go > 2).

**Comment by joshuarrrr** [comment]
@evamillan Are you currently collapsing your menu bar to some sort of expandable popover on mobile layouts?

**Comment by evamillan** [comment]
@joshuarrrr No, the menu bar is not optimized for mobile layouts yet.

**Comment by kgcreative** [comment]
Ok, team, i've taken another pass at this. @evamillan, please confirm that this approach would work for your use case. @joshuarrrr, please check me on making sure this makes sense from a grouping perspective.

I'm thinking about having a "Compressed" and "Expanded" header variants. Compressed is essentially the same design we have seen already.
![image](https://user-images.githubusercontent.com/3443142/171808793-1aea3eba-531a-40ab-ab06-cf1c5d0831b6.png)

The "Expanded" variant has a couple of subtle distinctions from the design today:
![image](https://user-images.githubusercontent.com/3443142/171808909-55d78798-73e4-45ce-8d6e-cb3078c3a63e.png)
1. We've moved the User + Help icons to the "bottom" bar, to be consistent with the "compressed" design.
2. I'm making an explicit callout to move "help" to the far right. This is because eventually, i'd like for help to trigger a push flyout that will allow us to add contextual help, rather than a popover.
3. I've added a "home" icon in place of the opensearch symbol next to the menu. @joshuarrrr, then intent there is this would allow the "loading" spinner to replace that icon to be consistent with the compressed design.
4. The top bar now only has the brand & additional menu (or icon) hooks. This will make adding branding changes a bit more explicit for those users that want customize the brand in the top bar and add additional functionality. 
5. Finally, I'm making a recomendation that when we trigger the menu, we move the "home" link below "recently viewed" (or remove it all togehter). The new header will link to "home" via the "mark" icon in compressed mode, or via the "home" icon in extended mode, so no need for additional extra repetition.

![image](https://user-images.githubusercontent.com/3443142/171810231-506e8033-6b50-4081-ad7e-9a048ed7af33.png)

**Comment by joshuarrrr** [comment]
@kgcreative I like this solution a lot. I'll add a couple more implementation details and plans I have for executing this.

I agree that it makes sense to remove the home link from the dropdown, particularly because of the feedback we've heard about the clutter in menu. There may be some short-term user impact as folks who are used to using it adjust, but we can make the new logo home button as discoverable as possible, by at least adding a tooltip.

**Comment by evamillan** [comment]
@kgcreative Yes, it looks like this approach would work for us, thanks!!

**Comment by kavilla** [comment]
[Groom]: We are okay with utilizing the `config/opensearch_dashboards.yml` to toggle this on and off. Stay away from advanced settings.

One risk: How plugins utilize these bars.

**Comment by joshuarrrr** [comment]
Opened https://github.com/opensearch-project/security-dashboards-plugin/issues/1007 to address popover consistency.

**Comment by joshuarrrr** [comment]
As part of the code review and release planning, we've made a couple more changes to what was last proposed. To summarize:

1. We've introduced a new branding configuration option `opensearchDashboards.branding.useExpandedMenu` to provide control over the header layout. For now, [it will default to `true`](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1586#discussion_r898818015), to maintain the current two headers. Any users who want to start using the new condensed, single header layout will be able to set it to `false`. (For `3.0.0`, we'll change the default to `false` as a breaking change).
2. Because we've moved all existing `navControls` insertion points to the bottom bar (see 1. below), any existing nav controls that need to remain on the top bar should use one of the two newly created locations: `navControlsExpandedRight` or `navControlsExpandedCenter`.

Otherwise I implemented @kgcreative's requirements (with **implementation details in bold**):

1. We've moved the User + Help icons to the "bottom" bar, to be consistent with the "compressed" design. **(We've actually moved all existing navControls to the bottom bar: `navControlsLeft`, `navControlsCenter`, `navControlsRight`)**
2. I'm making an explicit callout to move "help" to the far right. This is because eventually, I'd like for help to trigger a push flyout that will allow us to add contextual help, rather than a popover. **Done**
3. I've added a "home" icon in place of the opensearch symbol next to the menu. @joshuarrrr, then intent there is this would allow the "loading" spinner to replace that icon to be consistent with the compressed design. **(Note: while we use the home logo by default, if a custom mark is provided, we'll use that.)**
4. The top bar now only has the brand & additional menu (or icon) hooks. This will make adding branding changes a bit more explicit for those users that want customize the brand in the top bar and add additional functionality. **(See 2. above - we created two new navControl locations)**
5. Finally, I'm making a recommendation that when we trigger the menu, we move the "home" link below "recently viewed" (or remove it all together). The new header will link to "home" via the "mark" icon in compressed mode, or via the "home" icon in extended mode, so no need for additional extra repetition. **(Removed. In the expanded mode, the full logo also links to home.)**

**Comment by joshuarrrr** [comment]
After discussing with @kgcreative , we decided that the configuration option should be `opensearchDashboards.branding.useExpandedHeader` instead of `opensearchDashboards.branding.useExpandedMenu`

**Comment by seanneumann** [comment]
Video of Feature sign off. Note, we got feedback to make a change. 

https://user-images.githubusercontent.com/1413295/175714292-f477fd7f-81a6-4a27-9246-cc0427b0ebb8.mp4

**Comment by kgcreative** [comment]
Demo/Sign-off outcome: Approved, contingent on configuration naming changes.
