### ISSUE TITLE
[BUG] Unable to create coordinate map even if geo_point data exist

### ISSUE THREAD

**Issue by ohxodi** [opensearch-project/OpenSearch-Dashboards#1849]
**Describe the bug**
When trying to visualize coordinate data with geo_point type in a map, OpenSearch Dashboards is unable to find these kind of data.

**To Reproduce**
Create an index containing geo_point data. Verify that the data type is recognized.

Go to "Visualize" menu, click on "Create Visualization" and select "Coordinate Map". Choose the right index pattern as source of data.

Add a "Geo coordinates" bucket and select Geohash as aggregation. OpenSearch Dashboard is then unable to find a field with geo_point data type. The following error is displayed : "The index pattern logstash-logs-* does not contain any of the following compatible field types: geo_point"

**Expected behavior**
You should be able to select your geo_point field as it exists and is recognized.

**OpenSearch Version**
OpenSearch 2.0.0

**Dashboards Version**
OpenSearch Dashboards 2.0.0

**Plugins**
geoip plugin to convert src_ip in coordinates.

**Screenshots**
![image](https://user-images.githubusercontent.com/88543690/177420985-fde2691d-2546-48b8-b8bc-4c634ae4e7e1.png)
![image](https://user-images.githubusercontent.com/88543690/177421135-0a490f7d-43a1-4ab1-a84f-aae2aa4f0fb6.png)
![image](https://user-images.githubusercontent.com/88543690/177421262-967adf78-951b-462c-a540-982557d11ffd.png)

**Comment by manasvinibs** [comment]
Thanks for reaching out! I tried to re-pro the issue by creating a new index pattern document with `geoip.location` values set exactly same as yours in the screenshot. But I'm able to get the `geo_point` field types recognized and added on the maps. 

![Screen Shot 2022-07-08 at 1 08 29 PM](https://user-images.githubusercontent.com/105884062/178063257-b3a46343-b7c8-4161-8b0a-288a8a022c98.png)

![Screen Shot 2022-07-08 at 1 04 33 PM](https://user-images.githubusercontent.com/105884062/178063081-3cfdabf1-4816-4a13-b7ca-ebac9fc4a7ca.png)

![Screen Shot 2022-07-08 at 1 05 18 PM](https://user-images.githubusercontent.com/105884062/178063111-cfcbfa45-9290-473b-9646-7449f1f918e5.png)


Can you do a retry after updating the mappings of your index property `geoip.location `type to `geo_point `and see if it works? Also is it possible to share the logs data with us, so that we can try to re-pro the issue.

**Comment by ohxodi** [comment]
Thanks for your answer. As it was working for you, I recreated your basic example and it worked also on my side... The only difference I could notice was on index template where location was defined like that :
```json
"geoip": {
  "type": "nested",
  "properties": {
    "city_name": { "type": "text" },
    "continent_code": { "type": "text" },
    "location": { "type": "geo_point" }
  }
}
```
Whereas location was defined like that for the test :
```json
"geoip.location": { "type": "geo_point" },
"name": { "type": "text" },
}
```
I'm not sure the problem comes entirely from that but recreating my index with the index template written like that solved my issue.
Thanks a lot for your help.
