### ISSUE TITLE
[MD] Save and Edit page input validation

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#1973]
Description:
In the save and edit credential page, we need to do input validation and show inline message to give user information for guiding. 
![image](https://user-images.githubusercontent.com/109543558/184690199-a30ebb6b-0a51-448a-b070-8b4146963d2f.png)

**Comment by KrooshalUX** [comment]
<img width="713" alt="Screen Shot 2022-08-15 at 4 55 59 PM" src="https://user-images.githubusercontent.com/105819041/184755690-22d8d155-ca80-4f42-9f2a-a5d90c8eb71c.png">

Currently writing comprehensive guidelines - Can you please specify the following for each form field #'d : 
1) Min chars, max chars, what values are not allowed
2) Min chars, max chars, what values are not allowed
3) No validation
4) Assuming we can only check for a present value (no endpoint to check against)
5) Assuming we can only check for a present value (no endpoint to check against)

**Comment by KrooshalUX** [comment]
General guidance: 
If any field is missing a value or otherwise contains an error, the submit button should remain in disabled state
Do not check for values onFocus

Credential Title Field (1)  
- onBlur & onChange - check for any value. If blank, display inline error
- Preferably onBlur - check if value exists as a credential title object. If the value is not unique, display inline error (this may not be part of P0)

Credential Description (2) 
- onBlur & onChange - check for any value. If blank, display inline error

Username (4)
- onBlur & onChange - check for any value. If blank, display inline error

Password (5)
- onBlur & onChange - check for any value. If blank, display inline error

onSubmit: 
- check for unique value in Title field. If the value is not unique, present user with an inline error as well as a Callout Error below the page description before the form
- Return user scroll position to top 
- check for any disallowed characters in Credential Title and Credential Description (unsure if necessary, please verify) 
- form submission button should appear in error state until fields with error 

<img width="764" alt="Screen Shot 2022-08-16 at 8 32 54 AM" src="https://user-images.githubusercontent.com/105819041/184922519-004857b2-be1c-42ba-b44f-e5c52cc55c64.png">
