### ISSUE TITLE
[DSM] Add Data source icon

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2034]
pending after UX provide the icon resource.

- update src/plugins/data_sources/server/saved_objects/data_source.ts icon
- update in index pattern

**Comment by KrooshalUX** [comment]
@kristenTian is this an icon for the "Saved Objects" table?

**Comment by zhongnansu** [comment]
@kristenTian is this still on track for 2.4?

**Comment by KrooshalUX** [comment]
In a decoupled world, which we are working towards, all connections will be a data source connection - therefore this icon may be added noise within the UI. @kgcreative  wondering what your take is on this, and if we should design it or close this issue as not needed.

**Comment by kgcreative** [comment]
for document field types, we have icons for field types using (`tokens`). I can see a world where we have a "type" column that only uses an icon type as a token as well (would save space and help disambiguate). I think we need to explore this a bit more, since I could see [type icon] datasource.indexname -- my concern with this is if it would simply add extra potentially unnecessary visual noise.

**Comment by KrooshalUX** [comment]
I am moving this over to OUI repo for further exploration on if we will add it to the OUI Icon set.
