### ISSUE TITLE
[MD][Meta] Support SigV4 auth types for data source

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2110]

**Comment by zhongnansu** [comment]
Currently we have supported
- No auth
- basic auth

**Comment by zhongnansu** [comment]
Implementation Tasks
- [ ] #2921

**Comment by zhongnansu** [comment]
demo video with PR #3058 

https://user-images.githubusercontent.com/32652829/218179410-bf3d4ec9-3a40-48c2-b7a3-0251a18cc443.mov

**Comment by KrooshalUX** [comment]
@zhongnansu  This is a great demo, thanks for putting it together and syncing earlier. 

Two small bits of feedback: 
- I recommend removing the confirmations in the update password UI on the object details page (also as @kgcreative mentioned in the PR) 
- A nice to have to consider is converting the authentication type radio buttons to `OuiSelect` since we now have more than 2. I understand that currently the project only has the 3 and tbd on plans for adding more, so this is not blocking feedback as it can be added in a future state as well. 

Great job team!

**Comment by zhongnansu** [comment]
Updated UI for credential update modal
![image](https://user-images.githubusercontent.com/32652829/219523611-ed24032f-1968-48ac-83ef-7fcccd4ce735.png)

**Comment by zhongnansu** [comment]
Reopen. Not all task are completed

**Comment by zhongnansu** [comment]
This can be closed, as we released this feature in 2.6.0
