### ISSUE TITLE
[MD] Data source with wrong password connection in index pattern

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2386]
If a data source is created with wrong credentials, when user try to use it in index pattern creation. The current behavior will ask user to type in credentials (see screenshots). 

However even type in correct ones there, it won't help with the connection. Tested with this data source http://54.70.243.216/app/management/opensearch-dashboards/dataSources/2c080040-37ba-11ed-9c7d-b99e8398c755 on [index pattern creation](http://54.70.243.216/app/management/opensearch-dashboards/indexPatterns/create).

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/105667444/190937028-8ea7a770-2c83-4274-a29e-b3d37b0f940d.png">

The proposal is to change the prompt from asking for credentials to a user friendly error message.

**Comment by zengyan-amazon** [comment]
@zhongnansu can you take a look?

**Comment by kristenTian** [comment]
Please also test first create with wrong credential, then correct it using update data source, would it work in index pattern step.

**Comment by zhongnansu** [comment]
@zengyan-amazon @kristenTian 
- The reason of the pop-up by browser is because, to support Data source in index management, we use opensearch client instead of the original `legacy` client in `indexpattern -> resolve_index.ts`
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1dcf6fd54c5e24bc38e97805eae4425f8446f718/src/plugins/index_pattern_management/server/routes/resolve_index.ts#L62-L69

- Then at router level, the 401 response from `opensearch client` is being added with a [`www-authenticate` header, that causes the pop-up](https://stackoverflow.com/questions/9859627/how-to-prevent-browser-to-invoke-basic-auth-popup-and-handle-401-error-using-jqu)
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1dcf6fd54c5e24bc38e97805eae4425f8446f718/src/core/server/http/router/router.ts#L329-L333 

- The issue will still happen in index pattern if we use the original `legacy` client to resolve index, because if not explicitly specified `wrap401Error=false`, by default the legacy client adds this `www-authenticate` header to response header, by `decorateNotAuthorizedError()` https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1dcf6fd54c5e24bc38e97805eae4425f8446f718/src/core/server/opensearch/legacy/cluster_client.ts#L92-L97
 

#### Solution
-  Considering we are adding support of legacy client for data source, after that, index pattern will switch back to use legacy client, then we can set the caller option, to pass in `wrap401Error = false`. It will not set `WWW-Authenticate` header anymore

Related Issue/PR #2204,

**Comment by kristenTian** [comment]
Thanks for great details, what does `the service level` exactly means in option 1? If you already implemented, could you please share some code example.

**Comment by zhongnansu** [comment]
> Thanks for great details, what does `the service level` exactly means in option 1? If you already implemented, could you please share some code example.

In my PR, you can see `wrap401Error = false` was added as a default param in the `callAPI`. This is within the data source plugin. We don't need each caller to configure from their side. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2204/files#diff-442cda9a371f9aa2ce417631ddf7a8b80f9ec6ade15676b1cfe390f1c25b3fe7R109
