### ISSUE TITLE
[Research] Document Timeline visualization type

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2718]
- [x] [Research] Document `timeline` plugin
- [x] [Research] Document `vis_type_timeline` plugin

**Comment by ananzh** [comment]
# Research on timeline and  vis_type_timeline plugin

## Introduction
Currently, we have two Timeline related plugins exists in OpenSearch Dashboards (OSD) repo. One is Timeline application ([timeline plugin](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/timeline)) and the other one is Timeline visualization ([vis_type_timeline plugin](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/vis_type_timeline)) in Visualize. 

## Timeline application

### Activate timeline application
Timeline application is deprecated since kibana 7.0. If you want to activate and use Timeline as a separate application, you will need to set `timeline.ui.enabled: true` in the opensearch_dashboards.yml. Then run OSD normally and you will see `Timeline` at the right navigation bar with discover, dashboards, visualize and etc. as an application.

### Use timeline application

<img width="1521" alt="Screenshot 2023-02-08 at 18 33 03" src="https://user-images.githubusercontent.com/79961084/217890185-08e5bbf0-e800-4541-863b-1581df016a17.png">

Timeline application allows multiple timeline expressions and graphs. 

### Saved Objects
There are two ways to save the timeline application. Therefore, there are two saved objects.

#### Save entire Timeline sheet

* Choose `save entire Timeline sheet`

<img width="636" alt="Screenshot 2023-02-09 at 09 37 27" src="https://user-images.githubusercontent.com/79961084/217893950-4b2725da-3cd4-4fcb-a502-c707ce04077b.png">

* Save button calls saveSheet() which uses `savedSheet.save()`  to save in the timelineController. Here `savedSheet` is the saved object (type: SavedSheet). 
```
//src/legacy/core_plugins/timelion/public/app.js

function saveSheet() {
    savedSheet.timelion_sheet = $scope.state.sheet;
    savedSheet.timelion_interval = $scope.state.interval;
    savedSheet.timelion_columns = $scope.state.columns;
    savedSheet.timelion_rows = $scope.state.rows;
    savedSheet.save().then(function (id) {
      if (id) {
        toastNotifications.addSuccess(
          i18n('timelion.saveSheet.successNotificationText', {
            defaultMessage: `Saved sheet '{title}'`,
            values: { title: savedSheet.title },
          })
        );

        if (savedSheet.id !== $routeParams.id) {
          kbnUrl.change('/{{id}}', { id: savedSheet.id });
        }
      }
    });
  }
```

* However, when we click `open` in the top navigation and select the saved sheet. We only see the default expression.

<img width="1175" alt="Screenshot 2023-02-09 at 10 00 15" src="https://user-images.githubusercontent.com/79961084/217899068-df4e5658-9407-44b6-96a8-a1085392db42.png">


* The SavedSheet saved object details are:

<img width="790" alt="Screenshot 2023-02-09 at 00 34 46" src="https://user-images.githubusercontent.com/79961084/217896251-74889c13-201d-4644-bb82-0938e89a153e.png">

 The reference object is:
<img width="306" alt="Screenshot 2023-02-09 at 00 37 22" src="https://user-images.githubusercontent.com/79961084/217896484-0561cc63-5f37-4c44-b4ce-f246d65b8c5e.png">

* About multiple saved objects

Timeline application allows multiple timeline expressions and graphs. If there are more than one timeline expressions, all the expressions are saved in the `timeline_sheet` array. For example, we saved two expressions as test-2.

<img width="763" alt="Screenshot 2023-02-09 at 09 55 51" src="https://user-images.githubusercontent.com/79961084/217898085-76eb20ed-1e6e-4252-a086-249140785ebe.png">

However, when we click `open` in the top navigation and select the saved sheet. Same as one expression, we don't see any saved expressions.


#### Save current expression as OpenSearch Dashboards dashboard

* Choose `Save current expression as OpenSearch Dashboards dashboard panel`
<img width="630" alt="Screenshot 2023-02-09 at 09 37 33" src="https://user-images.githubusercontent.com/79961084/217893973-6beac811-b115-4389-bda9-030cf8e60deb.png">

* Save button calls saveExpression() in the timelineController. `savedExpression` is a SavedVis object, which has visualization (vis), visState (include expression). It calls save() in src/ui/public/courier/saved_object/saved_object.js to save the objects.  

```
// src/legacy/core_plugins/timelion/public/app.js

  function saveExpression(title) {
    savedVisualizations.get({ type: 'timelion' }).then(function (savedExpression) {
      savedExpression.visState.params = {
        expression: $scope.state.sheet[$scope.state.selected],
        interval: $scope.state.interval
      };
      savedExpression.title = title;
      savedExpression.visState.title = title;
      savedExpression.save().then(function (id) {
        if (id) {
          toastNotifications.addSuccess(
            i18n('timelion.saveExpression.successNotificationText', {
              defaultMessage: `Saved expression '{title}'`,
              values: { title: savedExpression.title },
            }),
          );
        }
      });
    });
  }
 
```

* SavedVis can only be open in the visualization page. Need to route to visualize and open. 
* The  SavedVis saved object details are:
<img width="831" alt="Screenshot 2023-02-09 at 00 30 13" src="https://user-images.githubusercontent.com/79961084/217896172-ea5aae8c-7e54-41ce-a284-272ed5f76fea.png">

We could see the expression is saved in VisState.

The reference object is:
<img width="250" alt="Screenshot 2023-02-09 at 00 37 03" src="https://user-images.githubusercontent.com/79961084/217900601-7d70e1b3-f3be-4353-afb8-796d2e68c577.png">

* About multiple saved objects

Only the last expression is saved. For the same example, we could see only `metric:"avg:machine.ram"` is saved.

<img width="703" alt="Screenshot 2023-02-09 at 10 11 43" src="https://user-images.githubusercontent.com/79961084/217901733-fef4a341-3151-487b-8a32-d76aea3eaf58.png">

When open the saved visualization, only see one timeline graph which matches the saved expression

<img width="724" alt="Screenshot 2023-02-09 at 10 12 21" src="https://user-images.githubusercontent.com/79961084/217901973-d2bb2664-d64f-43ee-944f-251771402f43.png">

**Comment by ananzh** [comment]
## Timeline visualization

### Create a timeline visualization

* Navigate to `Visualize` and click the `Timeline` icon.
<img width="623" alt="Screenshot 2023-02-09 at 10 18 49" src="https://user-images.githubusercontent.com/79961084/217904824-0dcf5732-2c76-4f8f-8acc-f6da7225359c.png">

* Enter the expression and adjust the time range then run.
<img width="1263" alt="Screenshot 2023-02-09 at 10 31 08" src="https://user-images.githubusercontent.com/79961084/217905757-e50775a0-3127-4d35-b81d-649de19e2ceb.png">

### Workflow
![timeline-visualization-workflow](https://user-images.githubusercontent.com/79961084/217888198-ca7e62b6-3539-4390-ba20-d6129540badb.jpg)


### Saved Objects

* The saved object type of timeline visualization is SavedVis. The details are
<img width="691" alt="Screenshot 2023-02-09 at 10 21 47" src="https://user-images.githubusercontent.com/79961084/217903629-d238854d-d13c-408e-98e5-2c89c70e92e0.png">

* The reference object:
<img width="222" alt="Screenshot 2023-02-09 at 10 21 06" src="https://user-images.githubusercontent.com/79961084/217903707-b757cc3f-c8d9-4133-ba54-6412cce66804.png">

* The saved object of timeline visualization is the same as the saved object created by timeline application if chooses `Save current expression as OpenSearch Dashboards dashboard`. Therefore, there should be no migration issue between these two. The saved object created from `Save entire Timeline sheet` in timeline application will have migration issue.

**Comment by ananzh** [comment]
Done the research and close it
