### ISSUE TITLE
Add a plugin config to define backend plugin dependency and research if it can be installed on cluster through opensearch API

### ISSUE THREAD

**Issue by manasvinibs** [opensearch-project/OpenSearch-Dashboards#2799]
Is your feature request related to a problem? Please describe.

Installing an extension should automatically installs OpenSearch extensions it depends on.

Description:
Installing a plugin does not install it's corresponding OpenSearch plugin. In fact the plugin assumes it's available. 

As part of this task:
1) Add a new key for example in this [file](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/opensearch_dashboards.json#L6) for the scaffolding script that allows developers to define OpenSearch extensions.
2) Research Opensearch API's to install the extension on opensearch, if not available add a warning saying the Opensearch dashboard plugin has a dependency on the corresponding data source opensearch plugin to let know the cluster admin. Do not stop the OSD process. 
 If API exist, then the installation script will read the config field and then call OpenSearch APIs to install the extension on OpenSearch. Ensuring error handling, for example, if OpenSearch extension doesn't exist as defined then fail to install the extension.

Additional context

**Comment by manasvinibs** [comment]
@kavilla can you take a look at this?

**Comment by kavilla** [comment]
Hey @manasvinibs,

First point I think is good. This should be a component so the OpenSearch Dashboards external plugin or extension has a mechanism from the developer to tell it that it has a corresponding OpenSearch external plugin or extension. Which was missing prior.

The second point is good as well. To call it out, the executable can list plugins but we shouldn't expect that an executable or bat file will be available since we wont know the location of OpenSearch it could be an external cluster. Perhaps if the API is available as well is it able to detect if the plugin is already installed.

Another mechanism is like a healthcheck API from OpenSearch for example if there is some default prepackaged API that we know all plugins have we can hit that. For example if it's localhost:9200/api/anomalyDetection/version or something, then we know it's available.
