### ISSUE TITLE
Persist the app parameters in the redux store.

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2898]
Currently vis builder lacks persistence for its own app data. The modifications user made when creating vis builder visualizations will get lost when refresh without save. The expected behavior is to persist all valid modifications when refresh. This should also work with both the URL and session storage, as user can change the settings under advanced setting.

App data persistence:
1. visualization state, style state, metadata state in the redux store
2. app filter
3. queries

**Comment by abbyhu2000** [comment]
Some approaches that I have tried:
1. Follow the existing implementation pattern of app persistence for other plugins, use state container, state storage and state sync utils. The app filter and query works fine, but run into some problems when integrating the redux store and the state container. Not ideal since vis builder has a different state management method. https://github.com/abbyhu2000/OpenSearch-Dashboards/pull/22
2. Introduce an extra dependency, redux-persist package, to achieve persistence for redux store. Currently it has built in support for session storage, but need to look more into implementation and research to hook it up with OsdUrlStateStorage. https://github.com/abbyhu2000/OpenSearch-Dashboards/pull/20
3. Implement persistence without using state container or state sync utils, but directly hook redux store with OsdUrlStateStorage, and it works fine with both the URL and session storage. https://github.com/abbyhu2000/OpenSearch-Dashboards/pull/21

**Comment by abbyhu2000** [comment]
Close this issue since the redux store persistence PR has been merged.
