### ISSUE TITLE
Add ability to create deeply nested context menus with grouping

### ISSUE THREAD

**Issue by sikhote** [opensearch-project/OpenSearch-Dashboards#2904]
**Is your feature request related to a problem? Please describe.**

There is not a way to do the following within a dashboard context menu:

1. Create N layers deep of nested panels. Currently, the grouping field only allows a single layer deep
2. Add custom content as an item
4. Easily add titles to a group of items
5. Add custom panels and link to them from items

**Describe the solution you'd like**

A way to easily create additional groups of items within the first panel and easily add additional panels to the entire context menu. Also, to be able to link items in the first panel to specific panels. Also, to create groups of items with titles and custom context.

**Describe alternatives you've considered**

I have tried the current grouping option, but it does not allow the desired behavior.

**Additional context**

This is to support a new feature within the Alerting dashboard plugin and the Anomalies dashboard plugin. Each plugin will need to create 2 new shared groups of initial panel items. Shared, meaning each plugin adds in a single item to each group. Also, one of the groups will need a title. Also, we need to order the groups. The items in the initial context menu should be able to link to other panels in the context menu that show custom content or new menu options.

Included are screenshots of the desired context menu. The first screenshot shows the initial panel, which has options to view the inner Alerts panel. The Alerts panel has options to view other panels as well and even open flyouts from those inner panels.

<img width="1437" alt="1" src="https://user-images.githubusercontent.com/24573542/202888085-aa7fdda4-dc7f-45f0-852b-2804b2733cc8.png">
<img width="1437" alt="3" src="https://user-images.githubusercontent.com/24573542/202888087-4c3d8a67-36ee-4fc0-936e-dbd2ca7bb18c.png">
<img width="1437" alt="4" src="https://user-images.githubusercontent.com/24573542/202888094-b7a0f28a-f47e-4d84-b16f-bfe74a59f41f.png">
<img width="1437" alt="5" src="https://user-images.githubusercontent.com/24573542/202888097-b95b41c6-8b3e-467d-9ccc-127ecb7d8139.png">

**Comment by joshuarrrr** [comment]
@sikhote Thanks for opening this issue, this makes the intent much more clear and understandable. I do have a couple questions and concerns.

1. It seems like this design changes some of the fundamental assumptions about UI actions

The `ui_actions` plugin seems to be a solution to a particular need - multiple plugins may want to self-register actions based on particular triggers (often button or table cell click events). It provides a nice UI that allows the user to choose from the multiple actions that may be registered. But fundamentally, those are intended to be single, particular _actions_ that cleanly map to the original trigger.

In contrast, these mocks imagine that the context menu rendered by the `ui_actions` is more of a modal experience, or generalized container for various UI inputs, controls, and forms. That may indeed be the direction we want to go, particularly with the panel actions in `dashboard`, but it seems like a different use case which may deserve a properly fit technical abstraction, rather than warping `ui_actions` into something else.

3. "Also, we need to order the groups." - what is the proposed design for this?

It's not clear from this issue which component is responsible for action ordering. But I'd argue that it needs to be determined upstream - in this case, likely by the `dashboard` plugin

6. "N layers deep of nested panels" sounds like we're opening a can of worms we may later regret

In particular, I think we'd need to further consider how a user can successfully navigate up and down the nested tree. Currently, the standard UX just provides a linked grouping header that exits the group, but I'm not sure that's sufficient in a deeply nested implementation (how to you get back to the root quickly, for instance?).

**Comment by sikhote** [comment]
@joshuarrrr thanks for the dialog.

1. Agreed, this is certainly expanding the ability of actions and the amount/type of content they can contain. I'm not sure if there's anything I can do to push this request forward in regards to any concerns for expanding how we add context menu options, but please let me know. Perhaps @lezzago can help out or find the right people to engage in this discussion.
3.  To provide more context for "order the groups", when adding context menu items, we would like the ability to group together X number of items. Each group itself  would have an `order` property, allowing certain groups to be above other groups. Perhaps some kind of standard would be helpful here, such as critical items have a `10` order and so on. The burden of ordering would be on the action—in the project I am working on, it is the alerting-dashboard-plugin that adds an action, and the action contains groups, and each group has a given order. The Dashboards code would then arrange groups based on those provided orders. So, Dashboards does the get final decision, so it could allow certain types of actions to have precedence if we wanted to do that at a later time.
6. I understand it sounds like a can of worms and perhaps we only want very simple actions—if that's the case, the project I am working on will need to be adjusted. Perhaps the team I am working with can chime in @lezzago 

As for navigating around a deeply nested context panel, as user could click away and click back. The UI provided by EUI does not have a "home" shortcut—what we are doing is nothing outside of the EUI guidelines, but using the tools appropriately is certainly important. If we are concerned about using the UI appropriately, perhaps that's more of a UX discussion and not so much a code-feature discussion.

**Comment by joshuarrrr** [comment]
@sikhote Thanks for all the clarifications, they make sense. The only item I'm still really struggling with conceptually is the group ordering requirement, which sounds like a complexity tangle we'd like to avoid if at all possible. But I'll take a look at the PR to see how you actually tackled these in practice.

**Comment by lezzago** [comment]
@joshuarrrr 

> It seems like this design changes some of the fundamental assumptions about UI actions

We need to use UI actions to add new menu options on the Dashboard visualization, so we can add plugin specific actions. If that is not the correct way, where should we do this? Then in that functionality we would have to incorporate the nested panels.


> "Also, we need to order the groups." - what is the proposed design for this?

@brijos @kamingleung @xeniatup Do you have any thoughts on this particularly?
@joshuarrrr Is there some standard on how we show this? I know we have something similar from the hamburger button to show all the plugins, so users can go to that specific plugin page.

> "N layers deep of nested panels" sounds like we're opening a can of worms we may later regret

Can we hardcode a max value restriction? @sikhote @joshuarrrr

**Comment by sikhote** [comment]
@lezzago @joshuarrrr  we can hard-code max values for how many Nested layers are allowed, but I suggest against this, because it would require further documentation and it might not be a straight-forward limit to implement. To me, above all, evaluating the designs we are implementing is the most constructive way to implement limits. Happy to proceed either way though.

@joshuarrrr as for the group ordering requirement, agreed it is the most brittle part of the implementation as a whole. An implementation that allows different plugins to utilize the same group, without the two plugins having any knowledge of each other, means there will be some design decisions about how we determine which items should be grouped (do they have the same name? the exact same order? maybe some other ID?)...I decided that if two groups from separate plugins have the same name, they become a group.

**Comment by ashwin-pc** [comment]
@sikhote I think this change fundamentally alters the idea of what `ui_actions` is meant to represent. While i'm not against that, the approach here seems too specific to the problem you are trying to solve and may need a deeper discussion on whether its
1. necessary for the feature you are trying to impliment
2. The right abstraction in the first place. 

There are a few things here that i agree can definitely compliment the existing `ui_actions` api.
1. Grouping: the existing ui_actions pattern already allows for adding new actions, grouping them with a title is an incremental addition to the pattern. with some sensible defaults I see this as a great addition to the feature
2. Priority: Adding some sort of order to the list also makes sense, although I would keep it a lot simpler and just allow for low medium and high priorities with medium being the default to keep it simpler while still allowing for some flexibility with the placement of the options.

The thing im not sure i want to introduce is:
1. custom ui: This works with the OUI context menu mental model but goes against the mental model of what `ui_actions` are. They are supposed to be simple actions for a trigger which use context menus when a single trigger can run multiple actions. If we want custom UI elements, we can actually follow the first example `ui_action` "hello world" where we trigger a modal on clicking the action and all the custom interfaces can reside inside it. This keeps the `ui_actions` api the same while allowing you to implement your feature.
2. infinite nesting: This is mostly okay but can be bad ux unless we can enforce some limits. One level deep is actually a good stopping point since its quite easy to lose context the deeper you go in the nesting since you lose context of the previous level.

**Comment by sikhote** [comment]
I think further discussion might require the UX folks and project owners to discuss how to proceed. For now, I might defer to @lezzago for thoughts on moving forward.

**Comment by sikhote** [comment]
Closing as our UX needs changed.
