### ISSUE TITLE
[CI] Templates to CI workflows

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2991]
There is a lot of redundancy when running the Windows and Linux [workflows](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/build_and_test_workflow.yml#L28). We can probably use a template or matrices to reduce the amount of redundancy and make it easier to read.

**Comment by mohitsaxenaknoldus** [comment]
Hey, I'd like to work on this. Can you please assign it to me?

**Comment by joshuarrrr** [comment]
@mohitsaxenaknoldus I can't actually assign it to you in GitHub, but consider it yours to complete for now. Do you have any estimate of when you might have a PR? No particular rush, just so we can check back for progress.

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus I assigned it to you. Do you have any estimate of when you might have a PR? No particular rush, just so we can check back for progress.

I'll try to open a PR in 2-3 days.

**Comment by jlabatut** [comment]
Hi @kavilla @joshuarrrr, it looks that this issue still does not have any PR for now, can I be assigned on ? I can submit one by tomorrow. Thanks

**Comment by joshuarrrr** [comment]
Sure @jlabatut , I'll update the assignment.

**Comment by jlabatut** [comment]
Since the [`ubuntu`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/build_and_test_workflow.yml#L32) jobs needs a specific container image (`opensearchstaging/ci-runner`), and the `container` keyword does not support the `if` condition, we cannot actually merge the Windows and Linux workflows using matrices ?
Or is there another way to do so, other than not using this specific image ?
