### ISSUE TITLE
Support red dot icons on buttons with call backs

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/OpenSearch-Dashboards#3046]
**Is your feature request related to a problem? Please describe.**

On the Dashboard page with multiple visualizations, we want the 3 dot button to show a red icon if there action to take based on some call back the button contains. Based on #2880, we want to show the red icon when there are active alerts from the alerting plugin. 

![red dot on dashboards](https://user-images.githubusercontent.com/7276393/206298214-81fe4528-463f-4caf-8982-73c13e01fb18.png)

**Describe the solution you'd like**

I would like the ability to register call backs or associate call backs from the external plugins (in this case Alerting plugin) to the buttons and icons, so they know to call the alerting plugin registered callback function to know if it should display a red dot or not.

**Comment by lezzago** [comment]
Proposed solution:

- Update the [EmbeddableOutput object](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8732b1ca1695c9311643585f5b05270e61d248b1/src/plugins/embeddable/public/lib/embeddables/i_embeddable.ts#L44) to support a new boolean attribute called something like `indicateActionToTake`.
- Make sure that if `indicateActionToTake` is true, update the [3 dot button](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8732b1ca1695c9311643585f5b05270e61d248b1/src/plugins/embeddable/public/lib/panel/panel_header/panel_options_menu.tsx#L107) to show the red dot

For testing purposes:
- In the [updateHandler](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8732b1ca1695c9311643585f5b05270e61d248b1/src/plugins/visualizations/public/embeddable/visualize_embeddable.ts#L381) function, make random scenarios to update `indicateActionToTake` to true to ensure the red dot it being displayed and removed correctly.

**Comment by ashwin-pc** [comment]
@lezzago thanks for opening this issue. I like the approach you've proposed of adding the boolean flag to the embeddable to indicate a notification. How do you plan on setting this flag since the embeddable is essentially rendered by the visualization plugin. Also I see a second indicator in the context menu, does this issue not cover that scenario?

**Comment by lezzago** [comment]
@ashwin-pc the idea is that as the `updateHandler` function, we will retrieve the alerts and anomalies from the saved objects and then use that information to decide if there should be a red indicator on the 3 dot button.

**Comment by ashwin-pc** [comment]
Thanks for the context, that makes sense. Can we call it something simpler though? `indicateActionToTake` seems like a mouthful and not immediately clear about what it does. `hasNotifications`, `hasEvents`, or even something as simple as `showNotificationIndcator` that makes it explicit about what the flag does.

Since these are API changes I want to make sure that we get the names right since they will be annoying to walk back on.

**Comment by joshuarrrr** [comment]
@lezzago Have you already looked at these? I haven't traced their usage yet, but from the names it sure sounds like what we're trying to do here:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8732b1ca1695c9311643585f5b05270e61d248b1/src/plugins/embeddable/public/lib/triggers/triggers.ts#L82-L94

**Comment by joshuarrrr** [comment]
We also already have rendering logic for `EUINotificationBadge`s as part of the panel header. I'd advocate for figuring out how to use this existing pattern and interface rather than restyling the context menu button to have a dot indicator:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8732b1ca1695c9311643585f5b05270e61d248b1/src/plugins/embeddable/public/lib/panel/panel_header/panel_header.tsx#L75-L112

**Comment by joshuarrrr** [comment]
Closing this issue, as it's no longer required for the updated UX guidelines, and we don't have clear enough user stories to justify adding this feature yet. @lezzago feel free to reopen if I missed something here.
