### ISSUE TITLE
Support aggregated view of all events that are associated to a paticular 

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/OpenSearch-Dashboards#3047]
**Is your feature request related to a problem? Please describe.**
Based on the proposal here, #2880, there should be a central view from a flyout to let registered plugins to display their data onto the flyout as seen below.  This flyout will be seen from a `View Events` button that will show up an a button option from a visualization in the Dashboard page. Below is an example of aggregating data from the Alerting, AD, and Notebooks plugins. 

![View Events](https://user-images.githubusercontent.com/7276393/206299667-4449d84d-b52a-4394-b005-6b304b36b976.png)

**Describe the solution you'd like**
I would like there to be a new flyout component that can let plugins register to it, so it can display all of the plugins data onto the flyout and correlate with the graph that is shown at the top. 

There are 2 proposals on how it shows the data:
1. Let plugins pass in `divs` that will let plugins have full control on how they display their plugin data on the page
2. Let plugins register functions that will provide the necessary data for the flyout to aggregate together and display it on the page.

**Comment by joshuarrrr** [comment]
I think we've discussed that the responsibility of registering events and plugins will be handled by a new plugin in core dashboards ("Panel event mangager" or somesuch? We should think of a name that captures it's purpose and use). So this issue is for defining the registration interfaces and data structures it will support.

Personally, I have a strong preference for 2., where the overall compositing and rendering is owned by the new plugin, with very specific and consistent interfaces for plugins to provide data. It's almost certain that we'll need to expand in the future for other use cases, but it's much easier to start narrow and well defined than to allow arbitrary content, which can become a maintenance and backward compatibility nightmare.

**Comment by ashwin-pc** [comment]
I second option 2. Infact this could be a great use of the expressions plugin to render plugin registered content into different sections of the panel

**Comment by joshuarrrr** [comment]
@ohltyler @lezzago Did you need any additional input from the OpenSearch Dashboards team on this? Or has it been superseded by other `vis_augmenter` issues?

**Comment by ohltyler** [comment]
This can be closed in favor of #3155
