### ISSUE TITLE
Allow disabling context menu options

### ISSUE THREAD

**Issue by sikhote** [opensearch-project/OpenSearch-Dashboards#3303]
**Is your feature request related to a problem? Please describe.**

We are looking to support UX situations where we want to display a menu option, but show it in a disabled/unclickable state. We can do this slightly already by changing the text color, but we cannot change the icon color and we cannot affect the mouse icon on hover for the entire item within the context menu.

**Describe the solution you'd like**

An option for disabling a context action, such as an `isDisabled` property that affects how the item is built within the context menu.

**Describe alternatives you've considered**

I have tried adding CSS to the title, but this is hacky and does not change the mouse cursor for the entire item.

**Example screenshot**

<img width="1455" alt="alerting plugin docs link" src="https://user-images.githubusercontent.com/24573542/213963799-b2d2ead7-57fb-49e1-b49d-b10d766b07df.png">

**Comment by ananzh** [comment]
AI: Help team understand the issue. List action items if needed. If it needs more discussion, pls add it to HOT TOPIC in the triage note.

**Comment by BSFishy** [comment]
OUI supports disabled context menu items:

https://github.com/opensearch-project/oui/blob/db0d86b9fdcb69b2231d6567810a82736f374f3c/src/components/context_menu/context_menu_item.tsx#L63

This is something that would need to be implemented in OSD. I'm not super familiar with how OSD handles UI solutions like this, but IIRC, there is some sort of context UI service that might be related?

**Comment by BSFishy** [comment]
@joshuarrrr or @ashwin-pc might have more context on this

**Comment by joshuarrrr** [comment]
Thanks for the OUI context @BSFishy. In OpenSearch Dashboards, this particular usage (the hamburger menu on panels in a `dashboard`), the relevant service is provided by UI Actions plugin: https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/ui_actions

The primary purpose of UI Actions is to allow components and plugins to separately define triggers and actions. Triggers are events that can be listened/subscribed to by actions defined elsewhere (including different plugins). So the usage of the `OUIContextMenu` is not directly accessible to integrators - it's just leveraged by the UI Actions service in cases where there are more than one action registered to the trigger (to allow the user to select/disambiguate which action they want). Otherwise, it will just execute the single action. 

From this context, the idea of registering an action that can't actually be executed is conceptually kind of weird (although it makes sense for a context menu). **What's the proposed behavior for a case where an inactive/disabled action is the only action registered?**

@kgcreative @KrooshalUX Can we have some more guidance on how we should be evolving UI Actions, or more info I can provide about the reasons for the existing constraints?

**Comment by sikhote** [comment]
That is an interesting case where the context menu does not have any enabled options available. In the UX flow I am working with, this would not be possible (there would always be one option available), but I understand how this situation could come about. @ashwin-pc would you be able to answer this or help reach out to the UX folks? We can also discuss in tomorrow's meeting.

**Comment by KrooshalUX** [comment]
@joshuarrrr In the case of visualizations on the dashboard, there should always be Maximize and Inspect, so I don't see a case in which the only registered action is inactive/disabled unless those actions were explicitly removed by a contributing builder. 

In the context of the proposed use-case, the registration of the disabled action is to coach the user on actions available once the alerting object is created. Mousing over the registered but disabled action reveals a tool-tip explanation as to why the item is disabled, which follows common guidance (which needs to be clearly codified in the OUI guidance (action item for @xeniatup - if the ? included in the design is to indicate the reason, this is not needed as the tooltip is already built-in, and can be removed) 

As far as your question regarding guidance on how to evolve UI Actions, can you be a bit more specific? Being general/vague-ish, I would like to ensure UI Actions can support all of the functionality that comes with OUIContextMenu , as we build more prescriptive guidance for designers and engineers to rely on the design system - gaps in the service may continue to cause churn across projects and contribution.

**Comment by KrooshalUX** [comment]
After giving this some more thought, I have some additional questions/concerns - since the disabled action that is being registered in this case is Manage monitors and will always direct the user to the full experience, does it make sense to just have it as an active item that directs the user to the manage experience, regardless if there are monitors or not? 

Do we actually want to keep an active count of the number of monitors? If we keep the count here, every time the user accesses the context menu - this action will need to trigger an API call to get the accurate count or whether or not there are active monitors. There is also a potential user experience issue with that, where menu items may end up in a loading state while waiting to retrieve a call back from the API. Is this a performance concern to anyone?

**Comment by sikhote** [comment]
@KrooshalUX I agree with your first comment, to always show the Manage Monitors, but this was passed-up in the past. Maybe things have changed.

As for the API call causing UX issues, that's somewhat of a concern and a good reason to not use the count in the context menu. I'm not aware of menu items having the ability to be in a loading state—it might just be that the content menu takes time to open without a loading indicator of any kind.

I might ask for some support from others on where to go with this concern.

**Comment by kgcreative** [comment]
I would advocate from removing (not disabling) if the plugin doesn't exist, and always showing the link to "manage" even when there are zero monitors. This is a jumping off point. The number of monitors is a nice to have, but perhaps we could not show ({count}) if the result is zero, null, or loading. (There is a pattern for loading data, where we can show a spinner while we fetch data)

**Comment by lezzago** [comment]
I believe that if there is still some pushback on the disable functionality, we can let users go to the manage monitors flyout, but there will just be a message letting users know they have no monitors associated to the visualizations and they need to associate one to the viz.

With this approach, we do not have to worry about dealing with the disable functionality.

**Comment by ashwin-pc** [comment]
@lezzago Can we close this issue since you have a workaround and removing context menu items is already possible if needed?

**Comment by sikhote** [comment]
Yes we can close 👍
