### ISSUE TITLE
[BUG]Serilog not sinking logs to Opensearch

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/OpenSearch-Dashboards#3379]
@VartikaSharma14 commented on [Fri Feb 03 2023](https://github.com/opensearch-project/OpenSearch/issues/6172)

Hello
I have installed Opensearch and opensearch dashboad 2.5.0 version from docker compose file.
Attached screenshot of code how I am sinking to elasticsearch. 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/99406269/216628737-3b8d39b4-8a7d-4387-a664-1757533d6276.png">

But when I check in opensearch dashboard -> No indices is created 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/99406269/216629147-d83d0d8a-2850-45b3-8ded-2a0eda35510c.png">

Also getting exception on console from serilog
<img width="944" alt="image" src="https://user-images.githubusercontent.com/99406269/216629242-47de2aae-239f-4964-92b4-c863f2c4117b.png">

As I am new to opensearch. 
kindly assist me I feel a little stuck.

Thank you 
Vartika Sharma

---

@minalsha commented on [Fri Feb 03 2023](https://github.com/opensearch-project/OpenSearch/issues/6172#issuecomment-1416254278)

@seanneumann  can you help?

**Comment by zhongnansu** [comment]
Not familiar with serilog. Could you help take a look? @joshuarrrr

**Comment by joshuarrrr** [comment]
@minalsha looking at the error message from the serilog console, it appears that the request to https://opensearch.org/docs/1.2/opensearch/rest-api/document-apis/bulk/ is failing, and that this is a data ingestion/indexing problem rather than an issue on the dashboards side. If the data is never indexed correctly, it makes sense that there's no way to create a matching index pattern. Was there any particular reason you believe this is an OpenSearch Dashboards issue?
