### ISSUE TITLE
Cleanup 1.x branch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#339]
I was confused what 1.x branch was vs. main vs. 1.0.0-beta1. Looks like 1.x was cut at some point but abandoned. As of the time of writing 1.0.0.beta1 = main, so 1.x has a set of changes that is confusing. I would nuke merge main -> 1.x to level all the things up and eventually increment version on main to 2.x (?).

**Comment by kavilla** [comment]
For 1.x, we have been cherry-picking commits from main into 1.x. Probably at the time this issue was created we haven't done a complete sync but now they are equal. We have some PRs to make it into main then 1.x but once those PRs are merged we will cut the branch out of 1.x, then update main to bump up the semantic versioning on main to which point main and 1.x will "diverge".
