### ISSUE TITLE
Add Link to UX survey into Dashboards

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#3521]
**Is your feature request related to a problem? Please describe.**

**What:** We are proposing that we add a link to the open source survey into the Dashboards open source experience. 
**Why:**  We need user input on the dashboard creation and consumption experience. Users intercepted and providing feedback on features elsewhere (such as [OpenSearch.org](http://opensearch.org/) etc.) lack the specificity required to improve the dashboarding experience.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1413295/222826628-e5553f50-749d-4efb-ae79-3a6d6cc3618a.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/1413295/222826851-3dd93baf-b717-4310-812a-2c91747d7037.png">

**Comment by seanneumann** [comment]
@dagneyb Can you provide any additional details?

**Comment by kavilla** [comment]
> @dagneyb Can you provide any additional details?

+1, will need to have a dedicated location and ability to configure this.

**Comment by apasun** [comment]
Need to make sure that the location accessed by the dashboard creator is tagged distinct from the location accessed by a dashboard viewer

**Comment by seanneumann** [comment]
> Need to make sure that the location accessed by the dashboard creator is tagged distinct from the location accessed by a dashboard viewer

@apasun I don't follow. Can you explain more?

**Comment by apasun** [comment]
Need to know if the user input would be from a consumer or producers. Both will overlap on tasks such as query, visualize, share etc.

**Comment by dagneyb** [comment]
@apasun the link should land the user onto the generic survey so that they can self-select their persona.

**Comment by dagneyb** [comment]
@apasun - please provide the link here. @kavilla ETA for the link is tomorrow. Do you think we can deliver this in 2.7?

**Comment by joshuarrrr** [comment]
As a Dashboards administrator, how do I disable this feature? How else can it be configured?

**Comment by dagneyb** [comment]
@kavilla here is the link: https://amazonmr.au1.qualtrics.com/jfe/form/SV_1BxJNrtCo4LbweW

@joshuarrrr great question. Is there somewhere we currently offer similar configuration options that we could add this to?

**Comment by dagneyb** [comment]
@abbyhu2000 can we update the text of the survey link to be "Give feedback" rather than "Satisfaction survey". Also, is it possible to make the updates recommended in the attached image, or will these need to go into a future release? 

![image (6)](https://user-images.githubusercontent.com/110415401/228386428-beabf864-bf0c-49ed-a6bf-6c859349fc42.png)

**Comment by seanneumann** [comment]
> As a Dashboards administrator, how do I disable this feature? How else can it be configured?

Can we provide a config option in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml?

e.g.
opensearchDashboards.feedbackUrl: "https://amazonmr.au1.qualtrics.com/jfe/form/SV_1BxJNrtCo4LbweW"

**Comment by abbyhu2000** [comment]
Since i am hearing different suggestions relating to this issue, just wish to get an agreement from everyone before i proceed. Here are the three options right now: 

1. Add a single link to the helper menu without configuring option
    * Pros: simplest and fastest option, since we are just adding a static link to the current helper menu. 
    * Cons: link is hardcoded, user will not have the option to enable/disable the link.

2. Add a config `opensearchDashboards.survey.enabled: true` in the `opensearch_dashboards.yml` 
    * Pros: give administrator option to enable/disable the link, the default is to enable the link
    * Cons: there are other links in the menu, and we are only giving one link this configurable option seems inconsistent

3. Make the entire helper menu fully configurable, as @kavilla suggests here https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676#discussion_r1148044907
    * Pros: all the links in the helper menu are fully configurable 
    * Cons: bigger scope, take more time; add more configs to the yaml file

Since we wish to get this feature in for 2.7, i think option 2 is the best choice right now. It might seem inconsistent that we only give the survey link configuration option from the helper menu, but because all the other links are just public GitHub links or forum links while the survey link is the only link that is provided by Amazon, I think users might care less about configuring those public links than the survey link. I do think option 3 is a good suggestion, but i think for this 2.7 issue we should keep the scope smaller. I could create an issue for option 3 if we wish to do this in the future release.

As for the UI changes proposed here , I agree with all the changes but just wish to get confirmation from the UI as well. @KrooshalUX @kgcreative 
<img width="937" alt="Screen Shot 2023-03-28 at 5 37 43 PM" src="https://user-images.githubusercontent.com/43937633/228397003-0a4b549f-9564-4486-9714-9d6f5e4c84b3.png">

However, i do not think it is a good idea to add the `Give feedback` link on the nav bar itself. I think it makes more sense to include it in the helper menu like the other links. 
<img width="559" alt="Screen Shot 2023-03-28 at 5 38 45 PM" src="https://user-images.githubusercontent.com/43937633/228397125-24e9835d-1691-455d-a76c-56e77662fc11.png">

What do you guys think and can we get an agreement on this? @seanneumann @dagneyb @kavilla @joshuarrrr @kgcreative

**Comment by dagneyb** [comment]
@abbyhu2000 thank you for the details provided, very helpful. I am aligned with approach #2. If possible, can we also update the text of the other menu items to the new names outlined in the graphic above. Note that @kgcreative created the graphic above, so he is aligned :). Thank you!

Additional question - is there any way for us to have the link to the survey reference a link stored elsewhere that we could dynamically update. We do not expect the link to change, and can update the survey at the same link, but in case something were to change in the future, it would be ideal if we could update the link for anyone running 2.7 without them having to upgrade. Let me know what you think.

**Comment by abbyhu2000** [comment]
@dagneyb Yea i can update the text and and link for the rest of the menu items outlined in the graphic above. 

For updating the link, maybe option 2 can be: 

Add config `opensearchDashboards.survey.url:"https://amazonmr.au1.qualtrics.com/jfe/form/SV_1BxJNrtCo4LbweW"` in the `opensearch_dashboards.yml`. The default is to enable the survey link; if user leave it blank, then the link will not be shown in the menu; and if we want to change the link in the future, we can change it in the `opensearch_dashboards.yml` file.

**Comment by dagneyb** [comment]
Thanks @abbyhu2000, I am aligned with your approach. Thanks!

**Comment by seanneumann** [comment]
Instead of setting the URL to the actual survey, can we create a DNS entry for feedback.opensearch.org (or something similar) and let the DNS redirect to the actual survey? It would be allow us to update to newer surveys as necessary. 

`opensearchDashboards.survey.url:"https://feedback.opensearch.org"`

**Comment by wbeckler** [comment]
Was there a PR that closed this?

**Comment by joshuarrrr** [comment]
It's linked in the issue close message: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676
