### ISSUE TITLE
[Research] Research and propose alternative math library option to replace Tinymath

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3656]
Since `Tinymath` is deprecated, we need to find alternative solution to replace tinymath logics. 

* Research on the usage of `Tinymath` in the repo
* Propose alternative options to replace those logics

**Comment by ananzh** [comment]
- [ ] Clean out other Tinymath usage
   * clean out in packages/osd-optimizer/src/worker/webpack.config.ts
   * clean out yarn.lock and package.json. check on documents and comments

**Comment by ltwmori** [comment]
Hi! I wanna work on this task. I came from here: #3655

**Comment by Aigerim-ai** [comment]
@Itwmori Hi! how is your task  going so far? let's work together?

**Comment by Aigerim-ai** [comment]
@Itmori how is it going so far? I came from #3657

**Comment by williamcaoliver** [comment]
@abbyhu2000 Hi! New here, but would like to contribute, is this issue fixed? If not I would like to help!

**Comment by joshuarrrr** [comment]
@ltwmori We haven't heard any updates for a couple weeks. Are you still working on this issue?

Because this is a research task, I think we can also work a bit in parallel - instead of making a PR. @williamcaoliver and @Aigerim-ai, feel free to add comments here as you begin researching alternatives and usage - that way we can all track the progress together without overlapping.
