### ISSUE TITLE
Allow index pattern fields to choose a default metric/bucket aggregation

### ISSUE THREAD

**Issue by JacobBrandt** [opensearch-project/OpenSearch-Dashboards#378]
**Is your feature request related to a problem? Please describe.**

There are many times where a field will be used in a visualization with a specific metric/bucket aggregation.  It would be really handy if the user didn't always have to select this but instead could assign a field in an index pattern to automatically select that metric/bucket aggregation for them.

**Describe the solution you'd like**
I would like a way for a user to set (from Index Management) a default metric & bucket aggregation to use when this field is selected in visualizations.

**Comment by joshuarrrr** [comment]
@ashwin-pc I don't think this is likely to be in scope for v2.5 of Vis Builder, but I'm going to tag it as part of the project, because it's an interesting feature we may want to keep in mind as we further refine these defaults.

**Comment by joshuarrrr** [comment]
@JacobBrandt You mention wanting to be able to set these from Index Management - but would it maybe be more convenient to do it from the visualization editor itself, through some sort of "remember this aggregation" checkbox or something?

**Comment by ashwin-pc** [comment]
@joshuarrrr This seems to be an issue that was opened before VisBuilder. I assume it was a way to make creating visualizations easier.

@JacobBrandt now that we have the new VisBuilder feature, do you think a feature like this is still relavant? I assume this was an ease of use feature to help speed up the process of creating a visualization. Now that we have a much simpler way to do so, do you think it makes sense to close this?

I also think that having field level control over the aggregation is not ideal since the aggregation would also depend on the visualization that we are trying to render and the axis of that visualization.
