### ISSUE TITLE
[FEATURE] OpenSearch Scope (Kibana Lens)

### ISSUE THREAD

**Issue by BenJammin18** [opensearch-project/OpenSearch-Dashboards#3785]
**Is your feature request related to a problem? Please describe.**

Working with a significant amount of data sets I find myself missing the Lens functionality from Kibana. 

**Describe the solution you'd like**

If there was a similar or even better capability to use multiple index patterns in a single visualization as well as the capability to shift and show visualizations across different data sets. That would be ideal

**Describe alternatives you've considered**

Have tried just making larger index patterns that encompass more datasets but it severely impacts performance. Have also tried mixed input dashboards but the inability to show which cards are from which datasource limits the ability to be digested easily.

**Additional context**
![image](https://user-images.githubusercontent.com/93599608/229895851-ac23ab5c-0b1d-448f-a6fd-d2cc24aa3e61.png)

**Comment by ashwin-pc** [comment]
@BenJammin18 Have you tried out [VisBuilder](https://opensearch.org/docs/latest/dashboards/visualize/visbuilder/)?

**Comment by BenJammin18** [comment]
Yeah VisBuilder is a good like 75% solution, but it doesnt provide me the capability i need to toggle back and forth across multiple inputs or aggregate from several index patterns.

**Comment by ashwin-pc** [comment]
Thats a good callout, can you add that feedback here so that it can inform our decision to prioritize the feature? https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2280. Thats a thing we have on the roadmap for the future since it involves adding support for layers, something we definitely want to do. 

Also I'll be closing this issue in favor of the feedback issue.
