### ISSUE TITLE
Creating link for DEVELOPER_GUIDE.md(if it is exists) or documentation  for Jenkins usage

### ISSUE THREAD

**Issue by Aigerim-ai** [opensearch-project/OpenSearch-Dashboards#3809]
I have started working on https://github.com/opensearch-project/OpenSearch-Dashboards/issues/773
However, Since I had no idea on how to run Jenkins on our Opensearch-Dashboard repository, I think we need to create step by step guide on how to run Jupkins for new users

**Comment by abbyhu2000** [comment]
Hi @Aigerim-ai, `Jenkins` is used to be the main automation tool for our CICD. It might be difficult for you to access our Jenkin pipeline, and I do not think it is necessary to add documentation on Jenkin in our developer guide since we not mainly use GitHub action for the CICD.

However, you can still finish this task without using Jenkin. 

The problematic unit tests are below in `src/cli_keystore/get_keystore.test.js`. If you read the function `getKeystore()` in `src/cli_keystore/get_keystore.js`, the rules are pretty simple. If there is a existing data keystore, we return data keystore path; if not, we return the config keystore path. However, the unit tests here are just using `toContain('config')` and `toContain('data')` to verify if the function is returning the correct path. It assumes that if the path contains the word 'config', then the function correctly returns the config keystore file path; and vise versa.

Instead of assuming this, could you rewrite the following two unit tests so they are actually checking the function `getKeystore()`  returns the correct file path of either data keystore or config keystore?

```
  it('uses the config directory if there is no pre-existing keystore', () => {
    sandbox.stub(fs, 'existsSync').returns(false);
    expect(getKeystore()).toContain('config');
    console.log(getKeystore())
    expect(getKeystore()).not.toContain('data');
  });

  it('uses the data directory if there is a pre-existing keystore in the data directory', () => {
    sandbox.stub(fs, 'existsSync').returns(true);
    expect(getKeystore()).toContain('data');
    console.log(getKeystore())
    expect(getKeystore()).not.toContain('config');
  });
```

**Comment by ashwin-pc** [comment]
@joshuarrrr @abbyhu2000 can we close this issue then?

**Comment by joshuarrrr** [comment]
Looks like we were able to close out #773, so this can be closed as well.
