### ISSUE TITLE
[Feature Anywhere] Performance test the new feature anywhere integration across OSD and plugins.

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/OpenSearch-Dashboards#3833]
We should have metrics we look at to make sure the new feature anywhere doesn't bring any degradation to cluster or current OSD as well as that feature anywhere itself holds to reasonable performance standards. This means testing out the limitations of changing the default number of associated objects per visualizations and any other new UI or visualizations that is part of the feature anywhere project.

**Comment by ohltyler** [comment]
We should also test some bulk deletion scenarios. Ref: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4059#discussion_r1198108624

**Comment by kavilla** [comment]
As called out: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3981

We will target this for v2.next for prioritization on Node upgrade.

**Comment by joshuarrrr** [comment]
@ohltyler @amitgalitz This is tagged for 2.9 release - is there any remaining work to be done here or updates on progress? Will there be any PRs to review?

**Comment by ohltyler** [comment]
This has been in progress - I'll post some comprehensive results here when completed. The initial testing showed some clear bottlenecks and led to 2 big improvements (one included in 2.9)
- #4608 
- #4595

**Comment by ohltyler** [comment]
Results:
![Screenshot 2023-07-26 at 1 03 21 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/62119629/742564c1-b4ec-46cf-af14-000f366c8310)

**Comment by ohltyler** [comment]
Conclusions:
- Overall association count has significant impact on loading dashboard. On 3-node cluster, 32s increase when processing 0 vs. 1000 associations
- Overall association count has significant impact on loading view events flyout. On 3-node cluster, 25s increase when processing 1 vs. 100 associations
- Loading time for view events flyout scales linearly. This make sense, since each visualization rendered in the flyout is executed sequentially, and rendered all at once when all of them have been created / render workflow completed. An improvement can be done to have these done asynchronously similar to a dashboard.
- No load issues in plugin flyouts regardless of overall association count
- Event count & time range had little to no effect. Ror example, rendering a vis with 500 events had the identical load times compared to rendering the same vis with 0 events. This shows that event fetching / event processing / bucketing / rendering of event datapoints scales fine. It makes sense since there is a fixed number of datapoints shown on the vega charts.
- Vis count did not have a huge effect. Since visualizations are rendered async on a dashboard, the overall count didn't have drastic impact. There was a noticeable effect with there is 20+ visualizations. For example, it took roughly double the time for a dashboard with 20 visualizations (each with 50 associations) to load (39s), than for a dashboard with 1 visualization with 50 associations (18s).

**Comment by ohltyler** [comment]
Next steps:

Finished:
- [ ] Only fetch related augment-vis saved objects that match the vis reference. Effect: much faster dashboard loading times. For details, see PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4595
- [ ] Only fetch related augment-vis saved objects that match the set of plugin resource IDs. Effect: much faster view events flyout loading times. For details, see PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4608

To do (optimizing client-side logic):
- [ ] Rendering visualizations - currently, it is a sequential approach to fetch each saved object, execute each plugin expression function, and concatenate results. A refactoring could be done to group all objects of a particular plugin into a single expression function. This would involve refactoring augment-vis objects to represent an association of a plugin resource type to a visualization, rather than a plugin resource to a visualization. And within that single association, could persist the set of plugin resources. When reading and executing, logic could be made to pass all plugin resources to a single plugin expression function which can do batch processing and return all concatenated results at once.
- [ ] Rendering view events flyout - this can be improved in multiple ways. For one, decoupling from embeddables may provide inherent speed-up since the rendering can be simplified, ignoring the added overhead of embeddable logic. Secondly, there can be big improvements in how data & events is fetched. For example, right now, each visualization is re-fetching the same source data (it is filtered out), + re-fetching the events for that particular plugin resource. Instead, this could be simplified to just fetching all source data & all events once, and passing on the particular subset of data to the individual visualizations as input. This would require decoupling from embeddables by default, since there is no way to pass data to embeddable visualizations; rather, just contextual input is passed, and data is fetched each time.

**Comment by ohltyler** [comment]
Related issues:

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4483
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4630
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4631
