### ISSUE TITLE
Remove Tutorials from "Add Data" page

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#426]
After reviewing the Tutorial Directory (/app/home#/tutorial_directory), we believe everything should be moved to our documentation site. For the purposes of this issue, remove all tutorials, keep the Sample Data options, and add a link to our documentation site. 

**Remove...**
![image](https://user-images.githubusercontent.com/1413295/120705473-bb21d200-c46c-11eb-99ec-f839eaac4586.png)

**Keep...**
![image](https://user-images.githubusercontent.com/1413295/120705520-c96fee00-c46c-11eb-99ab-98d41aa540df.png)

**Comment by seanneumann** [comment]
Docs URL to use for RC: https://docs-beta.opensearch.org/

**Comment by ananzh** [comment]
Team, it seems this issue request  think I need a clarification on how we want to change. If we delete everything just keep `try sample data` 
<img width="806" alt="Screen Shot 2021-06-08 at 9 43 54 AM" src="https://user-images.githubusercontent.com/79961084/121225328-4371ef80-c83e-11eb-9e2b-5e3e4c11f6a3.png">

Then we also need to make some changes on the home page. We should move "Try sample data" in the box?
<img width="534" alt="Screen Shot 2021-06-08 at 9 41 21 AM" src="https://user-images.githubusercontent.com/79961084/121225421-5ab0dd00-c83e-11eb-963d-fd6b9de38526.png">

We might need some designs and decisions here

**Comment by ahopp** [comment]
Thanks for the callout @ananzh! 

1. What do we think about pulling in the "Try sample data" and making the add data section explicitly for the sample for the time being? Once we get the "learn more", "quick start", and instructions updated we can add back the more generic content. it would read something like this;

      **Add sample data**
      Get started with sample data, visualizations, and dashboards

2. I'm not sure we need to resolve the redundancy on the following page (i.e. "Add data" header exists without meaningful subheaders) since we intent to revert and the landing CX isn't disruptive.
