### ISSUE TITLE
Remove unused `tutorials`

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#4448]
The repository has a lot of content under
* src/plugins/home/server/tutorials
* src/plugins/home/public/application/components/tutorial
* src/plugins/home/public/assets/tutorials
... among others

This are inaccessible and serve no purpose. We should get rid of them.

**Comment by CMDWillYang** [comment]
Can I work on this @joshuarrrr?

It would be appreciated if I can have more information regarding how to identify what contents are inaccessible and serve no purpose.

**Comment by joshuarrrr** [comment]
@CMDWillYang Thanks for picking this up! Yes, the original issue is a "stub" which means that the first step is to clarify what needs to be done and if it's possible to break the task into smaller pieces. The tutorial functionality was inherited in the fork, but is currently unused. 

As you've pointed out, some of these files may still be referenced, although unused, and removing the files will also require removing those references. If you're concerned that a particular reference is still needed or in use, post a link to the code here.

_Aside: instead of screenshots of code, GitHub has some nice tricks to link to source code. For example, if you highlight lines of code in GitHub and select "copy permalink" from the `...` menu, you'll get something like `https://github.com/opensearch-project/OpenSearch-Dashboards/blob/336dce65664cd1f541db33325e5787722443d9c6/src/plugins/home/public/application/components/home_app.js#L63-L111`. If you paste as-is into an issue or PR comment, GitHub will display a preview inline:

**Comment by joshuarrrr** [comment]
@CMDWillYang I'd start by searching for the routes you see defined here:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b3104ce6ca1af405426f59a447effd15ab2a6d4c/src/plugins/home/public/application/components/home_app.js#L90-L91

I started by looking `tutorial` and `/tutorial`, which both have a large number of results to comb through (including false positives where `/tutorial/` is part of the import path. There may be ways to further refine or target the search; alternatively, you can start by only removing the files you're most sure of, including the specific paths specified in the issue description.

I can confirm that we need to keep this route: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b3104ce6ca1af405426f59a447effd15ab2a6d4c/src/plugins/home/public/application/components/home_app.js#L63-L71

We still use it for loading sample data, as seen here: https://playground.opensearch.org/app/home#/tutorial_directory

**Comment by joshuarrrr** [comment]
@CMDWillYang I'd start by searching for the routes you see defined here:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b3104ce6ca1af405426f59a447effd15ab2a6d4c/src/plugins/home/public/application/components/home_app.js#L90-L91

I started by looking `tutorial` and `/tutorial`, which both have a large number of results to comb through (including false positives where `/tutorial/` is part of the import path. On the other hand `/tutorial/` is much more representative of what we're looking for.

Alternatively, you can start by only removing the files you're most sure of, including the specific paths specified in the issue description.

I can confirm that we need to keep this route: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b3104ce6ca1af405426f59a447effd15ab2a6d4c/src/plugins/home/public/application/components/home_app.js#L63-L71

We still use it for loading sample data, as seen here: https://playground.opensearch.org/app/home#/tutorial_directory
