### ISSUE TITLE
[BUG][Table] Regression issue when refresh table vis

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#4626]
### Describe the bug

Found a regression issue when refresh the table vis. Table is condensed after refresh. This happens after 2.7. 

* main branch

before the refresh
<img width="1259" alt="Screenshot 2023-07-26 at 10 33 18" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/8ffe812d-8aaa-4a79-a55e-fa69dabf2a30">

after refreshing the page
<img width="1768" alt="Screenshot 2023-07-26 at 10 44 46" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/7ffad3f1-115a-493f-ae9d-8ba510e92c95">

* 2.7
before and after refresh
<img width="1240" alt="Screenshot 2023-07-26 at 10 46 15" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/19df528a-d15e-4660-8dc6-722238766919">

**Comment by ananzh** [comment]
@curq I think this might be caused by your recent table vis PRs. Since you are an expert on table vis now, could you help us taking a look? 😄

**Comment by curq** [comment]
@ananzh Sure! I will check it out and try to find what might be the problem.

**Comment by curq** [comment]
@ananzh I figured out that the bug occurs because of this `FlexItem` component. Previously instead of it there was `<div>` element.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6bab7eff724913d4657a015b268fd6d00d7bfaf2/src/plugins/vis_type_table/public/components/table_vis_component_group.tsx#L21-L37
If we change it back to `<div>` the bug no longer is here.
before:
<img width="1286" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/67782303/92e5a0eb-1cc8-49c6-a71e-9c35096ea8fc">


after:
<img width="1282" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/67782303/4cd0284a-0a1a-42cc-b54e-698fee2e2233">

So it looks like some internal styles of `FlexItem` is messing up our layout. I gave it quick check but didn't seem to find what style is causing it. I will try looking deeper into it and try to pinpoint what exactly is the cause. What do you think?

**Comment by ananzh** [comment]
@curq this is a quick response. Thanks a lot. I think for now we should change it back until we found better solution.

**Comment by ananzh** [comment]
issue is resolved and PR is merged. close this issue.
