### ISSUE TITLE
[BUG] Update Dev Tools Documentation link under help in console

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/OpenSearch-Dashboards#4645]
**Describe the bug**

Update documentation link to Dev Tools documentation. Link currently goes to general OpenSearch Dashboards documentation. Link should go to Dev Tools documentation at https://opensearch.org/docs/latest/dashboards/dev-tools/index-dev/

**To Reproduce**
1. Go to 'OpenSearch Dashboards' main menu.
2. Select on 'Dev Tools'
3. In the Console, select the Help icon (question mark within a circle), then select Documentation. 

**Expected behavior**
Reader should be directed to the Dev Tools documentation main page.

**Dashboards Version**
2.9

**Screenshots**
<img width="1375" alt="Screenshot 2023-07-31 at 3 22 35 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105296784/f25fbc12-9ba2-422c-9d19-426d6e0e4980">

**Comment by joshuarrrr** [comment]
Thanks @vagimeli !

**Comment by Divyanshu975** [comment]
I will start working on this asap so , could you please assign it to me

**Comment by joshuarrrr** [comment]
Thanks @Divyanshu975 - Feel free to reach out if you have any questions.

**Comment by Divyanshu975** [comment]
Hey I following the developer_guide.md but after installing yarn's latest version in the main branch of open-search dashboard and running the command yarn install , I cannot execute the command 'yarn osd bootstrap' since it gives me an 'Internal Error' as follows:
![Screenshot 2023-08-16 162516](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112746483/d7c7d5bc-a7c3-4341-9257-915397d81653)

I've read forums and yet could not find a solution to this could you please help me out?

**Comment by Divyanshu975** [comment]
@joshuarrrr could you please help me out with the above issue

**Comment by Willie-The-Lord** [comment]
@joshuarrrr  I would like to work on this issue.

**Comment by joshuarrrr** [comment]
@Divyanshu975 Sorry I missed your earlier message. Can you provide some more info about your dev environment?

**Comment by vvavdiya** [comment]
@joshuarrrr 
I'd like to take a look at this, incase issue is still open.

**Comment by joshuarrrr** [comment]
@vvavdiya It looks like @Willie-The-Lord already has a PR open - let's find another issue to assign you to.
