### ISSUE TITLE
[BUG] `visAugmenter` requiring `savedObjectsManagement` puts other features at jeopardy

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#4671]
**Describe the bug**

A lot of visualizations indicate that they require bundles from `visAugmenter` who requires bundles from `savedObjectsManagement` and that requires the management plugin. If the `management` plugin is disabled everything falls apart.

Ideally, `visAugmenter` should gracefully degrade by not requiring `savedObjectsManagement` and checking if it is available before doing
```
uiActions.addTriggerAction(SAVED_OBJECT_DELETE_TRIGGER, savedObjectDeleteAction);
```

**To Reproduce**
1. Add `management.enabled: false` to the config
2. Restart and access OSD

**Expected behavior**
Everything should work

**OpenSearch Version**
Any

**Dashboards Version**
2.9.0

**Additional context**

#4642

**Comment by joshuarrrr** [comment]
Part of the underlying root cause is that `savedObjectManagement` takes dependencies in the wrong direction - it should provide a registration function instead of taking dependencies on `visualize`, `dashboard`, `discover`.

**Comment by ashwin-pc** [comment]
This is actually a problem with the way UI Actions is built. The issue as seen in the screenshot is because the ui actions break the whole app when we try to register an action to a trigger that isnt registered. The saved object management plugin registers the trigger `SAVED_OBJECT_DELETE_TRIGGER` and the visAugmenter plugin binds to that trigger. Now when the saved object management plugin is disabled, the trigger is never registered and the visAugmenter plugin during startup throws an error when it tries to bind an action against a trigger that does not exist. 

![Screenshot 2023-08-31 at 3 48 36 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/da4a2fd5-ada4-463f-82e7-4159dee5d64f)
