### ISSUE TITLE
[BUG] [Data Explorer] context URL for discover legacy plugin does not work

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4703]
**Describe the bug**
Previously URL such as `http://localhost:5604/rmx/app/discover/context#/...` will work and navigate to the discover page

After the data explorer change, the legacy discover now does not support URL such as `http://localhost:5604/rmx/app/discoverLegacy/context#/...`, this link will give 404 error. This is causing some functional tests in the context app in cigroup1 to fail.

**Comment by ashwin-pc** [comment]
Are you sure about this? 

Here is the playground URL for a discover that works: https://playground.opensearch.org/app/discover#/context/ff959d40-b880-11e8-a6d9-e546fe2bba5f/_vj8iYkBvcvNXZWo5GA-?_g=(filters:!())&_a=(columns:!(_source),filters:!())

The pattern you call out in this issue does not actually work in playground too: https://playground.opensearch.org/app/discover/context#/ff959d40-b880-11e8-a6d9-e546fe2bba5f/_vj8iYkBvcvNXZWo5GA-?_g=(filters:!())&_a=(columns:!(_source),filters:!())

Can you add repro steps on how you validated this?

**Comment by abbyhu2000** [comment]
Sorry for the type there, yea it should be /app/discover#/context/...
However, that still does not work for the legacy discover case

![Screenshot 2023-08-09 at 11 13 48 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/73a362ce-dd31-4463-9b8e-92abb74e7f15)

**Comment by ashwin-pc** [comment]
Hmm interesting. I think the issue is that the document ID is incorrect in the URL but its not because the URL resolution is failing. Here's how you can validate that:

1. Navigate to the view surrounding documents page in the legacy discover
2. Copy the URL and change `discoverLegacy` to `discover`
3. Navigate to the new URL
4. The context page should load

Now to get the error you are seeing, just modify the document ID to something that isnt a valid doc id and load the page again. This time you should see the error.

Figuring out why the doc id is incorrect should help fix this

**Comment by abbyhu2000** [comment]
Thanks, problem fixed
