### ISSUE TITLE
[BUG] Open search dashboard setup failing in local using MAC

### ISSUE THREAD

**Issue by gltestenv** [opensearch-project/OpenSearch-Dashboards#4799]
**Describe the bug**

Using the developer guid, I am trying to configure the open search dashboard in my local but getting the error
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#prerequisites
When running the command **`yarn opensearch snapshot`** getting below error.

`yarn opensearch snapshot
yarn run v1.22.19
$ scripts/use_node scripts/opensearch snapshot
 info Installing from snapshot
   │ info version: 3.0.0
   │ info install path: /Users/xxxx/Documents/xxxxx/Code/OpenSerachCode/OpenSearch-Dashboards/.opensearch/3.0.0
   │ info license: oss
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Daily general-availability snapshot URL not found for current version, falling back to release-candidate snapshot URL.
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc5/opensearch-3.0.0-rc5-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc4/opensearch-3.0.0-rc4-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc3/opensearch-3.0.0-rc3-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc2/opensearch-3.0.0-rc2-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc1/opensearch-3.0.0-rc1-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc0/opensearch-3.0.0-rc0-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ERROR Snapshots for 3.0.0 are not available
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Please provide help on this. Thanks in advance

**Comment by ashwin-pc** [comment]
@kavilla This issue should work based on https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2944. Do you know more?

**Comment by kavilla** [comment]
> @kavilla This issue should work based on https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2944. Do you know more?

Will need to check on my Mac, pontentially this could be an original time out with the bucket containing the artifacts needed to be updated.

Will still check, @gltestenv to be sure, would you be willing to share more information about your local machine. Are you running it through a VPN?

Are you able to download the snapshot link the error message first provides?

Thank you!

**Comment by ArielGMachado** [comment]
I am also currently having the same problem with my Mac with Apple Silicon processors.
Looks like the snapshot artifact recipe was updated by @kavilla  at that time via #3537 to support Darwin, but probably tested for x64 architecture only. This assumption is because in the build CI Jenkins there are only MacOS x64 (not arm64 Apple Silicon) nodes available as workers https://build.ci.opensearch.org/computer/
So this Jenkins CI does not generates native arm64 binaries.
When running `yarn opensearch snapshot` it is trying to download an artifact for darwing-**arm64** architecture `opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz` as detected for our Apple Silicon processor, artifacts that naturally do not exist in this artifactory.

That explains why the link to download snapshot for Darwin *arm64* fails : https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz

But the link to download the snapshot for Darwin *x64* works:
https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-x64-latest.tar.gz

**Comment by MrSparc** [comment]
@kavilla in the meanwhile the CI build pipeline was updated to support aarch64 by https://github.com/opensearch-project/opensearch-build/issues/4670 
Snapshots for Apple Silicon architecture are being built and available for download (the link in the previous comment for darwin-arm64 already works now), so this issue can be closed as fixed.

**Comment by peterzhuamazon** [comment]
Seems like this is fixed now per @MrSparc comments.
Glad the new snapshots helped here.

Closing now. Thanks.
