### ISSUE TITLE
[BUG][Data explorer] Whole page reloads when opening saved search

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#5066]
**Describe the bug**

When opening a saved search in the new discover, the page reloads with opensearch logo and text `Loading OpenSearch Dashboards`. This behavior is disturbing and doesn't happen in old discover

**To Reproduce**
1. Go to new discover
2. Click on save, save
3. Open the saved search
4. See whole page loading

**Expected behavior**
Page should update directly without loading logo/text, like old discover

**OpenSearch Version**
main

**Dashboards Version**
main

**Plugins**

no plugins

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
> any technical limitation making it expected behavior? it seems like a regression from old discover

Without looking deeply and @abbyhu2000 tell me if I'm wrong. The angular wrapper would basically treat navigating from the React app to the Angular parts of the card as a new location and was forcing a refresh. Now it could be that the application doesn't have to completely reload when navigating between the parts of the application and the Discover there can be a bad data state with existing behavior from Discover. Since Discover (and the Dashboard plugin) was built benefiting off this implementation and assumed that they did not have to care about a previous render state when in angular
