### ISSUE TITLE
[BUG] [Data Explorer] Save search rendering wrong on dashboard when refresh is clicked

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5116]
**Describe the bug**

The following functional test fail which cause cigroup2 fail. When we unload the index pattern data, and click refresh button, all the embeddables on dashboard should be refreshed and rendered empty; however, saved search did not get refreshed and still have the unexisting data.

```
describe('dashboard query bar', () => {
    before(async () => {
      await opensearchArchiver.load('dashboard/current/opensearch_dashboards');
      await opensearchDashboardsServer.uiSettings.replace({
        defaultIndex: '0bf35f60-3dc9-11e8-8660-4d65aa086b3c',
      });
      await PageObjects.common.navigateToApp('dashboard');
      await PageObjects.dashboard.preserveCrossAppState();
      await PageObjects.dashboard.loadSavedDashboard('dashboard with filter');
    });

    it('causes panels to reload when refresh is clicked', async () => {
      await opensearchArchiver.unload('dashboard/current/data');

      await queryBar.clickQuerySubmitButton();
      await retry.tryForTime(5000, async () => {
        debugger;
        const headers = await PageObjects.discover.getColumnHeaders();
        expect(headers.length).to.be(0);
        await pieChart.expectPieSliceCount(0);
      });
    });
  });
```

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/9f83db2e-7a2f-47a3-a4ca-3576d8b6f827

**Comment by ananzh** [comment]
When updating an embeddable in dashboard, the underlying dashboard container will call `reload()` for each embeddable. 
```
public reload() {
    Object.values(this.children).forEach((child) => child.reload());
  }
```
For new Discover, in search_embeddable, the reload function is designed to update the search properties when called. It does so by invoking the `pushContainerStateParamsToProps` function. The core of the issue lies in the isFetchRequired boolean within this function.
```
const isFetchRequired =
  !opensearchFilters.onlyDisabledFiltersChanged(this.input.filters, this.prevFilters) ||
  !isEqual(this.prevQuery, this.input.query) ||
  !isEqual(this.prevTimeRange, this.input.timeRange) ||
  !isEqual(searchProps.sort, this.input.sort || this.savedSearch.sort);
```
The above code checks several conditions to determine if a new data fetch is required. If any of these conditions evaluates to true, then data is fetched anew. However, when an index pattern currently in use by a dashboard is removed, these conditions may not detect any changes (e.g., in query, sort, time range). This means isFetchRequired remains false, preventing the data from being re-fetched.
