### ISSUE TITLE
[BUG] Filters are lost when reloading page or copying url to another browser tab

### ISSUE THREAD

**Issue by lbesuchet** [opensearch-project/OpenSearch-Dashboards#5179]
**Describe the bug**

Filters are lost when reloading page or copying url to another browser tab. 

**To Reproduce**
1. Go to https://playground.opensearch.org/
2. Click on Opensearch Dashboards / Discover
3. Select any index pattern (e.g: opensearch_dashboards_sample_data_flights)
4. Apply any filter (e.g: Carrier: OpenSearch-Air)
5. Copy the page url and paste it to another browser tab
6. => the filter has been lost (even if it is still visible in the url)

**Expected behavior**
Page is loaded with same filters as the original url

Note this works as expected when switching to the old Discover interface (not possible with playground.opensearch.org)

**Dashboards Version**
2.10.0

**Comment by Abilashinamdar** [comment]
I have gone through the code to get a fix for this issue and I found that injected metadata for 
`UI_SETTINGS.FILTERS_PINNED_BY_DEFAULT` in `ui_settings.ts` is **false** by default. Hence the filters are always pointing to `appState of FilterStateStore` rather than `globalState of FilterStateStore`.

Changing the value to `true` works as expected and here is the attached screenshot for the same:


![Screenshot from 2023-10-04 03-45-15](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/7028723/d1d1a144-840a-431b-a144-b7d29b4eba0b)

**Comment by jonashellmann** [comment]
@ananzh I would like to point out that this issue still exists with saved searches. Prior to finding this issue I opened #7677.
