### ISSUE TITLE
[BUG] Multiline content in [message] field is not displayed correctly 

### ISSUE THREAD

**Issue by vinylen** [opensearch-project/OpenSearch-Dashboards#5208]
**Describe the bug**

With the new discover UI we are unable to see multiline messages in a coherent way. Multiline messages just gets "stretched" out, never word wrapped. When switching back to the old discover UI, multiline messages gets displayed in a better way.

**To Reproduce**
Have multiline content in a field, toggle that field so that it is shown in the new discover UI

**Expected behavior**
Multiline messages should get displayed in the same way as before, showing a few lines.

**OpenSearch Version**
2.10

**Dashboards Version**
2.10

**Plugins**

opensearch-prometheus-exporter
s3-repository

**Screenshots**
New discover with multiline content, everything is just in a single row.
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/98466471/4e36a220-43fa-4636-bc02-f839a3a00f71)

Old discover with multiline content:
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/98466471/0f5c3605-2100-4cf7-b466-36e7ea6370ea)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by vinylen** [comment]
I can confirm the bug is also present in 2.11 - https://playground.opensearch.org/app/data-explorer/discover#?_a=(discover:(columns:!(products),isDirty:!f,sort:!()),metadata:(indexPattern:'3c72c3e0-6fa3-11ed-a8ec-958f39714b93',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_q=(filters:!(),query:(language:kuery,query:''))

**Comment by MadaniKK** [comment]
Hi, can I take this issue? Thank you

**Comment by joshuarrrr** [comment]
This may need to be fixed in the OUIDataGrid component.

**Comment by ananzh** [comment]
I think the bug is that in new Discover nested field is not correctly shown in left field nav. Here is how to reproduce it:

* step 1: go to dev tools. create an index and add nested field.
```
PUT test-2/_doc/1
{
  "products": [
    {
      "base_price": 28.99,
      "discount_percentage": 0,
      "quantity": 1,
      "manufacturer": "Tigress Enterprises"
    },
    {
      "base_price": 32.99,
      "discount_percentage": 0,
      "quantity": 1,
      "manufacturer": "Oceanavigations"
    }
  ]
}

PUT test-2/_doc/2
{
  "products": [
    {
      "base_price": 31.14,
      "discount_percentage": 5,
      "quantity": 1,
      "manufacturer": "Virora"
    },
    {
      "base_price": 35.69,
      "discount_percentage": 10,
      "quantity": 3,
      "manufacturer": "Oceanavigations"
    }
  ]
}

```
* step 2: go to `Dashboards management` --> `Index patterns` --> `create index pattern`
<img width="1612" alt="Screenshot 2023-10-25 at 12 49 21" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/f50862e1-5ee1-4935-a4cb-7d246cf21c8c">

* step 3: enter `test*` to match `test-2`
*  go back to discover. in the index pattern selector (on top of left nav), choose `test*`.

So in new Discover (2.11), if you check the left field nav, you could see we miss the nested field`products`. but the flyout and display are fine. It is just that there is no way customer could select nested field. 

<img width="1788" alt="Screenshot 2023-10-25 at 12 37 29" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/83b9775d-3eb4-4e0e-bb85-047951f00d85">

But if we do the above steps in 2.9 OSD with legacy discover, we could see `products` in left nav and once click `+` button to select it, you could see multiple lines in each row as customer shown.

<img width="1779" alt="Screenshot 2023-10-25 at 12 13 16" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/31624488-c4f8-4059-b0cd-b7df75a898a4">
<img width="1042" alt="Screenshot 2023-10-25 at 12 44 11" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/9fec8cde-7dd8-4dcf-8e87-f6d66a94a6d5">

<img width="1674" alt="Screenshot 2023-10-25 at 12 45 34" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/13083206-d204-444a-8e10-176b81205262">

I think we need to first solve the nested field not picked up by left nav then verify if we see multiline issue after select the nested field.

**Comment by MadaniKK** [comment]
Thank you for the detailed steps for reproducing the bug! Now I definitely understand more of the bug!  Which parts of the codes should I first try to look into? left field Nav and Datagrid?

**Comment by MadaniKK** [comment]
This issue is blocked by issue #5400

**Comment by ananzh** [comment]
resolved by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5429
now, given this fix, nested field in the object will be added as a separate field in side nav and table. 

@vinylen if there is more issues, pls reopen it.
