### ISSUE TITLE
[Data Explorer][Discover 2.0] Shared permalink/snapshot URL does not keep filters

### ISSUE THREAD

**Issue by karel-m** [opensearch-project/OpenSearch-Dashboards#5248]
**Describe the bug**

URLs shared as permalink/snapshot does not keep filters

**To Reproduce**

1. Go to - OpenSearch Dashboards >> Discover
2. Choose some columns (in my example: application,instanceName,message)
3. At this point the URL is:

_https://example.com/app/data-explorer/discover#?_a=(discover:(columns:!(application,instanceName,message),isDirty:!f,sort:!()),metadata:(indexPattern:'28a2fb90-2b97-11ee-8687-533761682be5',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_q=(filters:!(),query:(language:kuery,query:''))_

4. Add filter e.g. `instanceName = 123456`
5. Now the URL looks like this (seems fine as it contains the filter query):

_https://example.com/app/data-explorer/discover#?_a=(discover:(columns:!(application,instanceName,message),isDirty:!f,sort:!()),metadata:(indexPattern:'28a2fb90-2b97-11ee-8687-533761682be5',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'28a2fb90-2b97-11ee-8687-533761682be5',key:instanceName,negate:!f,params:(query:123456),type:phrase),query:(match_phrase:(instanceName:123456)))),query:(language:kuery,query:''))_

6. Go to menu >> Share >> Snapshot >> Copy link (the URL value is exactly the same in the previous bullet)

7. Open new browser windows + paste the "shared" URL - the view opens but the filter is missing

**Expected behavior**

I expect the filter should be applied after opening permalink/snapshot URL which was taken with an active filter.

**OpenSearch Version**

v2.10.0 (installed from RPM opensearch-2.10.0-1.x86_64)

**Dashboards Version**

v2.10.0 (installed from RPM opensearch-dashboards-2.10.0-1.x86_64)

**Host/Environment**
 - Server - Oracle Linux 8
 - Desktop - Browser and version: Chrome 117.0.5938.149 (Windows 10)

**Comment by ananzh** [comment]
@karel-m  Thanks for opening this issue. I also noticed this bug in our experimental discover 2.0 in 2.10 release. This is a duplicate issue of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5179 and we have resolved this issue with this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5206 in 2.11. I have verified again that this bug is gone. Though 2.11 is not officially released, we have cut a 2.11 branch in github. You could try it out. If the issue persists, feel free to re-open the issue.
