### ISSUE TITLE
Discover 2 has a small and non resizable logs panel

### ISSUE THREAD

**Issue by djboris9** [opensearch-project/OpenSearch-Dashboards#5260]
**Is your feature request related to a problem? Please describe.**

As a user of the Discover 2 (New Discover), we got a different layout of the search view than in the legacy discovery view. Compared to the legacy view, this results in a much smaller space in the panel where the logs are displayed and in a comparable large sidenav and histogram. As we usually use/look at the logs in the logs panel, we lost some productivity in this view.

**Describe the solution you'd like**

I see the following possible improvements as a non-UI-designer for the layout to improve the productivity:

- Make the navbar collapsable (#4780)
- Make the 3 different panels (navbar, histogram, logs) resizable
- Maybe reduce the blank space around each layout
- Maybe make the histogram collapsable

**Describe alternatives you've considered**

The following alternatives are currently used:

- Use devtools to remove the histogram
- Use a custom dashboard
- Use the legacy dashboard

**Additional context**

- OpenSearch Dashboards Version: 2.10.0
- Screen: 24in (1920x1200)

**Comment by kgcreative** [comment]
@ashwin-pc - let's explore using [resizable + collapsible panels](https://oui.opensearch.org/1.3/#/layout/resizable-container#collapsible-resizable-panels) for navbar, histogram & logs

**Comment by ashwin-pc** [comment]
@djboris9 Thanks for opening this, we've already fixed this issue in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5114. We've made the entire page scrollable like the legacy discover so the table should no longer only occupy the remaining space after the histogram and navbar. Adding a collapsible navbar as you called out is being tracked too, but will only make it in 2.12.

@kgcreative Yes thats the plan. I ran into some rerender issues which is why i punted it for now. WE will pick it up for 2.12 though. 

Closing this issue as a duplicate since one of the fixes (Whole page scrollling) is already implemented and the other (for the side nav) is tracked in #4780
