### ISSUE TITLE
[BUG] New Discover view - Refresh button does not work

### ISSUE THREAD

**Issue by opoplawski** [opensearch-project/OpenSearch-Dashboards#5314]
**Describe the bug**

Clicking on the Refresh button does nothing.  It seems to darken a bit  but no data is refreshed.

**To Reproduce**
1. Go to discover
2. Click on Refresh

**Expected behavior**
Data is refreshed to the latest available.

**OpenSearch Version**
opensearch-2.10.0-1.x86_64

**Dashboards Version**
opensearch-dashboards-2.10.0-1.x86_64

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-custom-codecs
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-neural-search
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-security-analytics
opensearch-sql

**Host/Environment (please complete the following information):**
 - OS: AlmaLinux 8
 - Browser and version 
 Firefox 115.3.1
Chromium 118.0.5993.70

**Comment by manasvinibs** [comment]
Hi,
Thanks for reaching out!

I did pull OpenSearch Dashboards 2.10 and was able to repro the issue for new discover. 

Issue - when I click on refresh button I do not see POST network call to cluster to read the refreshed Data.

<img width="1792" alt="Screenshot1" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/9292f6a5-fb67-49f2-8a77-6c8f4acd950f">

I toggled the switch back to old discover experience and I see refresh button works fine. 
You can see POST network call happening on clicking refresh button.


<img width="1791" alt="Screenshot 2" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/f73fa75e-f1cb-41b8-9059-807563d92a88">

I tried to repro the issue in 2.11 and it works fine. 

<img width="1791" alt="Screenshot 2023-10-17 at 2 07 57 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/2749c20f-b861-4fd5-847a-0a62ae138167">

I think new discover experience in 2.10.0 was introduced as an experimental feature and might contain few bugs as part of it which are identified and fixed in 2.11.0 version.

I would suggest you to toggle the experience to old discover in 2.10 or upgrade to 2.11 and let us know if you still see the same issue. If so, please share the reproducing steps.

**Comment by ict-one-nl** [comment]
Tested in 2.11: works as expect in Brave.
