### ISSUE TITLE
[BUG] Suggesting Empty Input in Search Field

### ISSUE THREAD

**Issue by Willie-The-Lord** [opensearch-project/OpenSearch-Dashboards#5348]
**Describe the bug**

The search feature suggests empty input as a valid option, leading to irrelevant or no results.

**To Reproduce**
1. Navigate to any section with a search query option such as 'Discover', 'Dashboards', etc.
2. Enter a whitespace or simply press enter.
3. Upon attempting to enter a new query, the suggestion history displays an empty option.

**Expected behavior**
The system should filter out empty strings and whitespace from the suggestion history to maintain a clean and relevant search experience.

**Screenshots**
![Screenshot 2023-10-20 at 9 13 08 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/65143821/015534fe-958c-4ffa-96d2-019b15b5c7fd)

**Comment by HimanshuMahto** [comment]
Hey, would like to work on this issue. I'm new to this so could you please help me with this

**Comment by Willie-The-Lord** [comment]
Hi @HimanshuMahto, I've just started a PR for this issue, you can look for another one to work on. I recommend starting with issues labeled as [good first issue](https://github.com/opensearch-project/OpenSearch-Dashboards/labels/good%20first%20issue) :)

**Comment by HimanshuMahto** [comment]
okkay

**Comment by zhongnansu** [comment]
@opensearch-project/opensearch-ux Please help confirm the correct UX

**Comment by Willie-The-Lord** [comment]
Thank you @zhongnansu and @ruanyl for your insights! I'm not entirely sure what the best practice is, but I came across a post on UX Stack Exchange that offers several options for handling empty queries. You can check it out [here](https://ux.stackexchange.com/questions/49080/what-should-be-fetched-if-you-search-with-a-blank-query).

**Comment by kgcreative** [comment]
I'm aligned with removing empty & blank spaces from the autocorrect suggestions. We should still allow the user to search for an empty string, and that's probably a sepparate issue.

**Comment by joshuarrrr** [comment]
Just to back up one step - @kgcreative it might be helpful if you could provide guidance on the purpose of these historical query suggestions. I think we've agreed here that we're not trying to provide a comprehensive history of searches (as obvious from the fact that we de-dupe the list). But should we also filter out invalid searches as well (such as the example in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5326)?

**Comment by kgcreative** [comment]
So i think we have a couple of options here. I think there could be value in showing invalid searches, but if we show them, then we should also show that it's invalid somehow (maybe a red ⚠️ in place of the "search" icon?). This also makes me think that should have a configurable option of "Show invalid queries in search history" in the "Discover" advanced settings tab. I think the intent of this is to show a searchable list of recent searches starting on empty state in order to help users pick up from previously used searches. With that in mind, knowing that a particular search is invalid could be useful, but perhaps not the default behavior? (@joshuarrrr, i'm open to additional suggestions here)

I think my long term proposal would be:
Show an explicit "recent searches" category above all the searches, and then also an indicator of invalid queries, with a way to toggle between showing all recent queries, or only show valid queries.

Extra long term would also be to introduce better auto-complete / expression builder to make it easier to compose DQL queries
