### ISSUE TITLE
[BUG] Discover Tab Search doesn't work

### ISSUE THREAD

**Issue by liamhess** [opensearch-project/OpenSearch-Dashboards#5468]
**Describe the bug**

In the Discovery tab of the new 2.11 Dashboards the index pattern search bar doesn't work. I tested it on a colleague's MacOS Sonoma and it also didn't work.

**To Reproduce**
1. Ingest a lot of unnecessary indices
2. Create index patterns
3. try to search for them in the discovery tab

**Expected behavior**
Usually it should filter the index patterns so that only the ones are visible that match my search.

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**

I used the default docker-compose from the quickstart with no plugin modifications so to my understanding it has the Security plugin and I don't know what else

**Screenshots**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/49128538/6e59d3dc-3002-46e3-b13c-9962cc10c8eb

**Host/Environment (please complete the following information):**
 - OS: MacOS Sonoma 14.0
 - Browser and version: Arc Version 1.15.1

**Comment by AMoo-Miki** [comment]
Thanks Liam for pointing this out.

**Comment by abbyhu2000** [comment]
Were able to reproduce this bug. 

This bug seems to be caused by this commit https://github.com/opensearch-project/OpenSearch-Dashboards/commit/1e980fac7a6dee3a1904511d2ae0f477575e6135. After removing the commit, the search functionality works fine. @AMoo-Miki @kavilla 

This commit also adds two extra white line to the bottom of the drop down list which looks buggy. Could you take a look at this bug? @mengweieric

**Comment by amirkkn** [comment]
The fix is not still available in container image 2.11.0 and 2.11.1. Could you please give a release time for this fix?
