### ISSUE TITLE
Try to see the first dashboard

### ISSUE THREAD

**Issue by SalvoDiMa91** [opensearch-project/OpenSearch-Dashboards#550]
Hi,

I would like to study this project and I'm trying to download, install and run the docker on my Windows PC.
I installed Docker and all components as described in this page: **https://docs-beta.opensearch.org/** but if I try to see an empy dashboard on the page: **http://localhost:5601/** I can see only the message " _OpenSearch Dashboards server is not ready yet_ ".

On Docker Dashboard I can see:
1. opensearch-dashboards running (port: 5601)
2. opensearch-node2 exited
3. opensearch-node1 running (port 9200)

How I can proceed? Any suggestion?

Thanks in advance
Salvo

**Comment by kavilla** [comment]
Hey @SalvoDiMa91,

For sure! Currently, the documentation remains in a beta state. It has content gaps and might contain bugs. After looking at the content the steps for setting up Dashboards seem a little bit confusing since it tells you to docker pull and then have a docker compose file with the contents to start docker containers. I would avoid that and do one or the other.

> OpenSearch Dashboards server is not ready yet

Basically means it can not connect to a node and it looks like it is your node2 since it is showing that it crashed with "opensearch-node2 exited". On your windows I'm guessing by following the directions your heap size might not be large enough by default.

I think the best route to test the stack would be to kill any containers you have right now and follow these directions here: https://opensearch.org/downloads.html, under the section: Try OpenSearch with Docker Compose.

Let me know if you run into any more issues. If not and you are able to successfully explore the application then we can close this issue and possibly open an issue in the https://github.com/opensearch-project/documentation-website repo.

**Comment by kavilla** [comment]
Closing this issue for now @SalvoDiMa91, please feel free to re-open if you are still having issues.
