### ISSUE TITLE
AWS Serverless ECS monitoring

### ISSUE THREAD

**Issue by damiancancela** [opensearch-project/OpenSearch-Dashboards#5621]
Hello,

i was searching here and there if there is a way to integrate AWS ECS with AWS Serverless OpenSearch solution, but unfortunately im not able to find any documentation.
Can someone please help me with this?

I think this is not for the serverless option
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/firelens-example-taskdefs.html

Thx

**Comment by ashwin-pc** [comment]
@damiancancela This is the OpenSearch Dashboards repo. This repository is responsible for the front end of OpenSearch. I think a better place to ask questions about how to use OpenSearch would be the user forums https://forum.opensearch.org/ or on the public slack channels. 

This being said, OpenSearch Serverless is the same service, just that Amazon manages the clusters for you instead of having you manage them yourselves. Details mentioned in the link you provided should work fine with the serverless option. But take that with a grain of salt since i have never personally used the serverless option myself (yet).

Closing this issue since there inst an issue or something thats related to OpenSearch Dashboards directly
