### ISSUE TITLE
[Bug]: Filter by type is by default 3, it should be 0. 

### ISSUE THREAD

**Issue by Kritika-Girdhar** [opensearch-project/OpenSearch-Dashboards#5650]
### Describe the bug

Filter by type by default is 3, and if we select 3 filters in it , it is 3 with highlighted red color.
It seems like it will be difficult for a colour-blind person to differentiate the two. earlier it used to be 0 which did specify that how many filters are selected.

Attached are the file which shows without selecting and with selecting the filters.

With 3 filters selected:
![filter_by_type_3_selected](https://github.com/opensearch-project/opensearch-build/assets/155047942/5713cf79-8c03-460c-83a0-f7199d5a7557)

With no filter selected:
![filter_by_type_3](https://github.com/opensearch-project/opensearch-build/assets/155047942/2e202ddb-b69f-4d7f-ac2f-54db37abcfe3)

### To reproduce

Go to Discover and click on any index pattern from the dropdown list.
See default value of Filter by type with selected all 3 filters and then without selecting any filter.
You will see that both time it is 3.

### Expected behavior

There should be some difference between when all 3 filters selected and when none , as it is difficult for a colour-blind person to differentiate.

### Screenshots

Older version
![image](https://github.com/opensearch-project/opensearch-build/assets/155047942/129fa790-de26-42e9-a2c0-a3fe2a0a0965)

Latest version
![image](https://github.com/opensearch-project/opensearch-build/assets/155047942/1b86246a-18d1-4ba9-8e72-22740558f246)

**Comment by ashwin-pc** [comment]
@Kritika-Girdhar which version are you referring to when you mention the old version? The reason i ask is because the way the way this behaves is dictated by the OUI component [`<OuiilterButton />`](https://oui.opensearch.org/1.4/#/forms/filter-group%23filter-buttons) which as you can see in the documentation shows by default when no active filters are present the number of filters available to the user. This is different from what you expect which is that when no filters are selected the filter count should show as 0.

cc: @kgcreative  @shanilpa

**Comment by Kritika-Girdhar** [comment]
Hi @ashwin-pc ,
The older version I am referring to is 2.9.0.

**Comment by kgcreative** [comment]
I think [0] when no filters are selected (and there fore there are many fields available) is more in line with user expectations. Once we open the filter group, we definitely can add more context. I don't think it's necessarily an accessibility issue, since there *is* enough luminance difference between the empty state and the selected state, however, it does lead to confusion when the cleared out state shows "available" fields, versus "filtered" fields. Let's take a pass to review the OUI documentation page, and to think about what the deault behavior should be (cc: @canascar), and then let's make sure that in discover we are showing the right experience as well. (cc: @shanilpa)

right now I would bias for "let's keep the filter behavior stable with 2.9", since you could argue that the new component default behavior is at least a bug, if not a regression.

**Comment by ashwin-pc** [comment]
Ive created an OUI issue to track the default behaviour https://github.com/opensearch-project/oui/issues/1219 since this will be closed when discover changes its behaviour.
