### ISSUE TITLE
[BUG] Multiple datasource's datasource id should be required if there is no opensearch hosts config

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#5699]
**Describe the bug**

Multiple datasource's datasource id should be required if there is no opensearch hosts config, we should check if datasourceid is empty or datasouce context is empty and there is no opernsearch hosts specified, then the request is invalid.  

**To Reproduce**
Send empty datasourceid with empty opensearch.hosts in the yaml config returns 500.

**Expected behavior**
We should check if the datasource Id is empty and return 400 instead of 500.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

N/A

**Screenshots**

N/A

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version: firefox 115.5.0esr 

**Additional context**

N/A

**Comment by xinruiba** [comment]
@Flyingliuhub Will take a look. Thanks

**Comment by xinruiba** [comment]
Noticed this is a new type of client "asCurrentUserWithLongNumeralsSupport" get introduced in from this PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b5d39b6e651ecf6c32fc87d6f8f893a86d48e3f2/src/plugins/data/server/search/opensearch_search/decide_client.ts#L18

Based on that change, if we turn on both MD and LongNumeralsSupport, LongNumeralsSupport will not be picked.

Will schedule a quick sync up meeting with "Miki Barahmand" to make sure that is the expected behavior.

**Comment by Flyingliuhub** [comment]
This is duplicate for #5880
