### ISSUE TITLE
Allow switch between legacy table and EuiDataGrid: Add an option to enable or disable the EuiDataGrid (2.11 table) for user preference.

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5716]
Propose to provide two ways for customer to switch between legacy table and data grid table.
* Use a new advanced settings `Use legacy table`
<img width="1698" alt="Screenshot 2024-01-22 at 1 44 34 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/e2198d74-4ec8-42a0-a3f7-77389be618cd">

* Use the switch table toggle on Discover page

<img width="1705" alt="Screenshot 2024-01-22 at 1 40 10 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/f41f2078-d37e-4afe-9afa-caf2c631bfc4">

<img width="1713" alt="Screenshot 2024-01-22 at 1 44 05 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/92e57ff4-db5d-437c-b141-7e37455bfae2">

**Comment by ashwin-pc** [comment]
@ananzh Can we make both the toggle behave the same way? Right now it looks like one toggle activates the legacy table when turnd on and the other activates the new table when turned on. 

Also i'd probably call it `newDiscoverExperience`. This lets us bundle all the changes into one instead of just the table. @shanilpa @dagneyb what do you think?

**Comment by shanilpa** [comment]
@ananzh I like that we have the setting accessible through advanced settings as well as in the application (plus 1 Ashwin's comment)

I do have additional feedback for the in app toggle. It feels detached from the component that is changing (which is okay) if we provide a description on what the change could entail. Additionally, we are missing the chance to collect feedback on the new table. Here is my suggested UX for enabling new features we would like users to try.


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113368824/785dac1b-ed4c-4947-8753-93998a389075



cc @kgcreative, @ashwin-pc, @dagneyb

**Comment by ananzh** [comment]
@ashwin-pc I see. Good point. Will modify the advanced settings to `Use new table`. Regarding `newDiscoverExperience`, you mean the toggle on the discover page? or in the advanced settings description? I would recommend `New table` since only table is updated. The side nav is updated as well as query/filter bar position.

**Comment by ananzh** [comment]
@shanilpa @ashwin-pc Thanks for the quick feedbacks. Let me summarize what we need to change:
* Change `Use Legacy table` to `Use New table` and modify descriptions accordingly. So default is `disabled`/`off` for both toggle and advanced settings.
* Change `New table` toggle to `Try new Discover features`. When click it, it will pop up a helper with 1) similar descriptions as in advanced settings 2) Enable new table 3) `Share feedbacks on github` and link to https://github.com/opensearch-project/OpenSearch-Dashboards/issues

**Comment by dagneyb** [comment]
@ananzh sounds good on the update to the advanced settings phrasing to align with the in-line selector. I agree with @shanilpa 's feedback that we should bring the toggle closer on the UI to the element it is impacting. I'm not fully aligned with the UI @shanilpa proposed in the video above however. The goal should be that we dont have multiple features being enabled/disabled at a given time, we should keep it really simple for each release with 2 options, not giving an on/off switch for all features. With that said, could we align on a toggle experience that makes it more obvious in this release that it controls the table, and if we use a toggle in a future release to try out a new Discover experience with multiple changes, that toggle would go back to the high level location proposed in the original issue here. Thoughts?

**Comment by ananzh** [comment]
I think `Enable new table` is the only option right? `Enable new feature` is just something we might expand in the future right? 

@shanilpa  and @dagneyb could we make a decision whether we want to use a single toggle or something like the mock with only one  `Enable new table`?

**Comment by shanilpa** [comment]
@dagneyb we can have a checkbox in the modal that says enable all new features so users can select all without having to click individually. I do think the granular control has several benefits:
1. User transparency on what is going to change and to what (especially if we bundle changes in Discover)
2. Allows users to pick and chose what functionality they would like based on their workflows (it isn't all or nothing)
3. Allows deep links if users want to provide feedback on a specific change

For this specific change since it is only the table if we can have the control closer to the table like in the original issue I think that works: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5555#issuecomment-1843521978 (plus it sounds like users are okay with the placement of the toggle there)

**Comment by ananzh** [comment]
Since table is only switchable component and given a tight timeline to mitigate users pain, we will keep a simple toggle to avoid any complexity and confusion.  Meanwhile, we already have an established feedback mechanism (accessible via the `?` icon) that our customers are familiar with. This feature has been a part of OSD from the start. We won't introduce a separate feedback channel specifically for the new Discover which might lead to redundancy. Based on the discussion, I would like to confirm the changes

* Keep toggle but change `New table` to `New Discover Experience` (@shanilpa Is this too long? Would like to have ur confirmation.) in the top nav as shown in the above.
* Add a dismissable notice (@shanilpa which way you prefer?)
  * Add notive like we did in 2.10 that lets the user know about the toggle and also points to them that they could click `?`  to provide feedback. 
  * Add a notice like we did in 2.10? because customer should be familiar with our feedback loop.
* Change `Use Legacy table` to `Use New table` and modify descriptions accordingly in the advanced settings. So default is disabled/off for both toggle and advanced settings.

**Comment by shanilpa** [comment]
Since we need this on a short turn around I am okay with the toggle. We can validate if this is the best implementation long term for future releases.

- We can change New table to New Discover experience @vagimeli does this work from a copy perspective?
- We can add the dismissible notice. The `?` feedback form is for general feedback and has questions that are too general for what we need. I can see users get frustrated with the form and not leave feedback. I think we should deep link to a specific Github issue or forum post so it's easy for users to provide feedback. @ananzh let's work with @vagimeli to get the copy for this banner as well.

**Comment by wbeckler** [comment]
What do you think about making this setting browser-specific by way of Josh's new browser-based theme settings? We would put the switch next to the table.

**Comment by dagneyb** [comment]
@wbeckler This should definitely be browser-specific if we can. @ananzh is that possible in time?

**Comment by vagimeli** [comment]
From a user POV, the button style is more eye-catching than the toggle. I suggest revisiting the design style, especially when we release more robust features.

**Comment by kgcreative** [comment]
> What do you think about making this setting browser-specific by way of Josh's new browser-based theme settings? We would put the switch next to the table and wire it up to the interface that Josh created in #5652.

This should be a per-user setting in the fullness of time, so individual users can decide for themselves which experience they want to use.

**Comment by shanilpa** [comment]
@ananzh here is the updated prototype with the toggle.
@vagimeli has reviewed the copy as well.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113368824/e5f88745-1773-443e-96a0-8bc655b01118

**Comment by vagimeli** [comment]
> @ananzh here is the updated prototype with the toggle. @vagimeli has reviewed the copy as well.
> 
>  New.featuresc2.0.mp4

LGTM!

**Comment by ananzh** [comment]
@wbeckler will check Josh's PR and update.
@vagimeli and @shanilpa I have made the changes based on the requests, pls help me to verify. The recording including the new table feedback panel in both light and dark mode and the changes in advanced settings.


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/d8b8c8cb-1b8e-4cf7-9842-21544c06a2a0

**Comment by shanilpa** [comment]
This looks good @ananzh. @kgcreative @dagneyb? 

Couple questions and feedback depending on the answer:
1. Is the survey opening in a new tab? If not it should. 
2. For the survey we should chat with Aparna to get a specific one for this feature. We shouldn't use the general Dashboards survey. @ashwin-pc did this in the past and should be able to help you out on how to get this. If not lmk and I can see if we can get that.

**Comment by ananzh** [comment]
@shanilpa 

Will update
1. Allow the survey opening in a new tab.
2. Will ask Aparna for a special one for feedbacks.

**Comment by ananzh** [comment]
Update based on request to use local storage and remove advanced settings to avoid any risk for customers


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/d45f064a-19e2-4ba1-8915-c87ad534af59

**Comment by kgcreative** [comment]
Thanks all!

A few small updates - Users expect that a toggle will switch the interface immediately, so having a full page refresh based on a toggle breaks that expectation. Let's align to using a (small) empty button with icon left instead in stead of the toggle:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3443142/19613093-1d3d-4070-a457-e6e6f737a0fa)


Then, for the go-back experience, let's update the modal to the following:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3443142/e443b021-29ef-4e0a-b352-4b134bfea618)

Title: `Share your thoughts on the latest Discover features`
Body: `Help drive future improvements by providing feedback about your experience.`
Primary Action: `Turn off new Discover`

**Comment by ananzh** [comment]
Resolved in [#5789](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5789)

**Comment by ohTHATaaronbrown** [comment]
So, this got implemented in 2.12. Great. I can't use that because my OS back-end version is *not 2.12*. That makes this toggle completely unreachable for me.

**Comment by wbeckler** [comment]
Are you self-hosting or are you using AWS's managed service? This is getting fixed as a patch to v2.11 on the managed service.

**Comment by ohTHATaaronbrown** [comment]
I self-host OSD against a managed OS cluster, because the built-in OSD makes all kinds of assumptions about security and access that don't fit my use case. This should be back-ported to a 2.11 patch, period. For all release paths of 2.11. The new table just breaks huge swaths of the functionality of the app.

**Comment by wbeckler** [comment]
@ananzh @ashwin-pc thoughts?

**Comment by ashwin-pc** [comment]
@ohTHATaaronbrown for your usecase you can add `opensearch.ignoreVersionMismatch: true` in your yaml config or pass the `--opensearch.ignoreVersionMismatch=true` flag in the CLI if thats how you run it to run OSD 2.12 against OS 2.11. This should not cause any issues since 2.12 should be backwards compatible with any 2.x version of OpenSearch

**Comment by ohTHATaaronbrown** [comment]
> ValidationError: [config validation of [opensearch].ignoreVersionMismatch]: "ignoreVersionMismatch" can only be set to true in development mode

**Comment by ashwin-pc** [comment]
@ohTHATaaronbrown Oh I wasn't aware that Dev mode was required to enable that. Yes that is silly and a restriction that we inherited from Kibana when we forked. @AMoo-Miki should have a way to unblock you temporarily until 2.13 which is also coming to AWS soon.

Honesty we had a tough call to make on what releases we could support for this fix since each release is quite time consuming, thats why for this toggle and the two user groups we targeted were Open Source users (using 2.12) and AWS users (using 2.11 since they would not get 2.12). I didn't anticipate anyone who isnt a dev from using a 2.11 AWS version with a 2.12 OpenSource in a production environment since thats not something that we've publicly supported even though its technically possible and probably safe to do.

Given that the 2.13 release is already underway I'll let @AMoo-Miki comment on how to get around the dev mode restriction temporarily until then.

**Comment by ohTHATaaronbrown** [comment]
I'm a troublemaker by nature. Sorry about that :)

**Comment by AMoo-Miki** [comment]
@ohTHATaaronbrown you are my favorite kind of user!

The upcoming version of OSD, 2.14.0, will allow you to use `opensearch.ignoreVersionMismatch: true` in the config file without forcing you into dev mode.

**Comment by AMoo-Miki** [comment]
@ananzh can this be closed?

**Comment by chadmyers** [comment]
@AMoo-Miki I just saw the release notes for Dashboards and saw your pull request. Thank you!

**Comment by ohTHATaaronbrown** [comment]
@AMoo-Miki Thank you!

**Comment by ashwin-pc** [comment]
Closing this issue since 2.14 has been released and you no longer need to be in dev mode to ignore the version mismatch.
