### ISSUE TITLE
[BUG] adding a "required bundle" throws an error during build even if its used

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#6018]
**Describe the bug**

Adding "dataSourceManagement" as a required bundle throws an error during building. 

```
 ERROR in /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/plugins/security-dashboards-plugin/opensearch_dashboards.json
         │          Bundle for [securityDashboards] lists [dataSourceManagement] as a required bundle, but does not use it. 
```

Even if I use it. Found a similar issue reported here: https://discuss.elastic.co/t/build-error-when-using-kibanareact-and-kibanautils-in-kibana-3rd-party-plugin/261748/3

**To Reproduce**
1. Add "dataSourceManagement" as a required bundle
2. Use it
3. run `yarn build`

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
Hi @derek-ho, can you share how it is added to the opensearch_dashboards.json file?

**Comment by derek-ho** [comment]
Adding it like this:
```
...
  "optionalPlugins": [
    "managementOverview",
    "dataSource"
  ],
  "requiredBundles": ["dataSourceManagement"],
....
```

**Comment by BionIT** [comment]
Thanks @derek-ho ! After some investigation, we found requiredBundle is only for built-in osd plugins to share modules, and for external plugins, we need to consume with optionalPlugins: ["dataSourceManagement"] - `yarn build` is successful after making this change, but node scripts/build_opensearch_dashboards_platform_plugins.js failed due to OSD complains about the plugin imports a bundle which is not from requiredBundle nor required plugin. To move forward, we can expose the react component as function by the data source plugin similar to https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/plugin.ts#L249, thanks to @ashwin-pc for the suggestion! It works locally, and will create a PR to export the component this way.
