### ISSUE TITLE
[MDS] Expose DataSourceMenu types for plugin consumption

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#6271]
With the DataSourceMenu refactor, some changes were made to expose a common config for all types. However, this is currently taking in Any: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/74e0df3b86e5d70b11a7c2eb03082b09e0f985c5/src/plugins/data_source_management/public/components/data_source_menu/types.ts#L25, so it is hard for plugins to consume this/know what to put as the type. 

Can we expose the type to plugins and/or enforce it when passing in the value?

**Comment by derek-ho** [comment]
Same issue with constants. I am seeing the following error:
```
 ERROR in ./public/apps/configuration/top-nav-menu.tsx
       │          Module not found: Error: import [../../../../../src/plugins/data_source_management/public] references a public export of the [dataSourceManagement] bundle, but that bundle is not in the "requiredPlugins" or "requiredBundles" list in the plugin manifest [/Users/dxho/Desktop/OpenSearch-Dashboards/plugins/security-dashboards-plugin/opensearch_dashboards.json]
       │           @ ./public/apps/configuration/top-nav-menu.tsx 17:0-99 37:46-69 37:87-110
       │           @ ./public/apps/configuration/panels/auth-view/auth-view.tsx
       │           @ ./public/apps/configuration/app-router.tsx
       │           @ ./public/apps/configuration/configuration-app.tsx
       │           @ ./public/plugin.ts
       │           @ ./public/index.ts
       │           @ /Users/dxho/Desktop/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js

```

When trying to do:
```
import { DataSourceComponentType } from '../../../../../src/plugins/data_source_management/public';

```

**Comment by seraphjiang** [comment]
@zhongnansu would you discuss with @derek-ho about this enhancement

**Comment by zhongnansu** [comment]
> @zhongnansu would you discuss with @derek-ho about this enhancement

@derek-ho Hi Derek, are you still having this issue? I think with the correct `configType` generic type passed in, when you first retrieve the `DataSourceMenu` component via API. It will enforce the ` componentConfig` to use param from the configType you chose, otherwise it throws compile error

An example usage as shown in the MD picker example plugin

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c89d3047d46ca809b6540c0fab8db33c6e736c09/examples/multiple_data_source_examples/public/components/data_source_selectable_example.tsx#L42

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/d3bd08a2-20aa-4b0b-8f72-58aef4898cd3)
