### ISSUE TITLE
[MDS] Refactor several utility functions in data source plugin

### ISSUE THREAD

**Issue by huyaboo** [opensearch-project/OpenSearch-Dashboards#6417]
**Is your feature request related to a problem? Please describe.**
Currently, there are two functions being repeated in plugins that can simply be extracted into data source plugin utility functions:
- A function that decides whether to use local cluster or remote OpenSearch client based on data source id
- A function that retrieves the data source id based on data source title/name

**Describe the solution you'd like**
There should be three utility functions placed in the data source plugin that will be exposed so that other plugins can consume:
- `decideClient(context: RequestHandlerContext, dataSourceId?: string, withLongNumeralsSupport: boolean)`: return the correct client
- `decideLegacyClient(context: RequestHandlerContext, dataSourceId?: string)`: return the correct legacy client
- `fetchDataSourceNameById(client: SavedObjectsClientCommon, dataSourceTitle: string)`: return the data source id (if it exists)
    - `SavedObjectClientWrapper` should be defined in both `public` and `server` folders for passing type checks

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by bandinib-amzn** [comment]
Thank you for continuous improvement and insist on high standards.

**Comment by BionIT** [comment]
@huyaboo Should we target this for 2.16 instead?

**Comment by zhongnansu** [comment]
Unlike "decideClient" that will be used by many internal and external plugins, where plugins need to choose the correct client to talk to either local cluster, or data source cluster, for "fetchDataSourceIdByName", I don't think it's necessary to make it a util in data source plugin, because 
1. it's only being used in vega and timeline plugin, I am not aware of any other internal or external plugins that needs it. 
2. there's context specific logic in the existing [fetchDataSourceIdByName](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4f54049fc2ffe2977c40e4de0869967a23dba5ff/src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.ts#L11C14-L11C37) function,  see below for example. "data_source_name" is very specific to the timeline/vega expression use case. So it doesn't make sense to make it general

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4f54049fc2ffe2977c40e4de0869967a23dba5ff/src/plugins/vis_type_timeline/server/lib/fetch_data_source_id.ts#L38-L41


cc: @huyaboo @BionIT

**Comment by BionIT** [comment]
Hi @zhongnansu Is this complete? Can we close the issue?

**Comment by zhongnansu** [comment]
> Hi @zhongnansu Is this complete? Can we close the issue?

Yes, closing
