### ISSUE TITLE
[BUG] tutorial shows incorrect URLs and platforms

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/OpenSearch-Dashboards#647]
**Describe the bug**

At `/app/home#/tutorial/systemLogs` the tutorial shows links to non-existent, webpages, tools, and platforms.

Examples:
https://www.opensearch.org/guide/en/beats/filebeat/main/filebeat-module-system.html -> 404
https://www.opensearch.org/guide/en/beats/filebeat/main/filebeat-installation-configuration.html -> 404
https://www.opensearch.org/downloads/beats/filebeat -> 404
https://artifacts.opensearch.org/downloads/beats/filebeat/filebeat-1.0.0-darwin-x64.tar.gz -> 404 (and incompatible version)

**To Reproduce**
1. Go to `/app/home#/tutorial/systemLogs`
2. Click on almost any link
3. Get 404

**Expected behavior**
This page should not exist.

**OpenSearch Version**
1.0 GA

**Dashboards Version**
1.0 GA

**Plugins**

Full bundle

**Screenshots**

<img width="1904" alt="Screen Shot 2021-07-14 at 7 54 39 AM" src="https://user-images.githubusercontent.com/1152927/125634930-05f483d9-ddce-406d-8f97-b710ac782ac4.png">

**Host/Environment (please complete the following information):**
 - OS: macOS
 - Browser and version: Chrome 91

**Additional context**

The links to this (and perhaps similar) tutorials seem to be removed but users can still directly access these via existing documentation or information.

**Comment by kavilla** [comment]
As you called out we removed the ability to navigate within the application to hit the tutorial page, but left the code and routes pretty much intact in case we want to re-use the content once we have replacements.

We basically didn't want people to go to the page but you could directly go to if you know the route or have a bookmark. My proposal is to remove the tutorials from the router, however now if somebody goes directly they will still get a 404. So do we think that is okay since it is technically solving a 404 with a 404.

**Comment by stockholmux** [comment]
@kavilla That makes sense.

**Comment by kavilla** [comment]
> @kavilla That makes sense.

Sounds good we can use this issue to remove the tutorials from the router.

**Comment by kavilla** [comment]
This issue will encompasses this issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/373
