### ISSUE TITLE
[BUG] Startup fails with theme overrides

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6704]
**Describe the bug**

![Screenshot 2024-05-02 at 12 15 07 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/f9258ee4-761e-4317-ab65-f0de322af1ac)
![Screenshot 2024-05-02 at 12 15 15 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/2b488be6-72bf-43eb-8370-7169bc8d3b71)
![Screenshot 2024-05-02 at 12 15 25 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/45768161-2512-435e-9fad-bc37f0c49ed8)

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
checkout a commit older than this PR would resolve thus narrow down to this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652

**Comment by BionIT** [comment]
Different from the screen recording in the PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6703

The dashboard in future playground won't display anything

**Comment by BionIT** [comment]
Found issue still happening, thus re-opened

**Comment by BionIT** [comment]
Yep, @joshuarrrr this is after switching to an older commit than the PR which introduced the bug, otherwise, we see empty page. Do we prefer an empty page? There is another bug in observability, already pinged owners.

**Comment by joshuarrrr** [comment]
I just need more info to be able to debug it, so if there was a version that included https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6703 and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652, that would be really helpful, because it doesn't repro running locally. I can also provide some additional context:

The issue is likely not in `/bootstrap.js` (source: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/legacy/ui/ui_render/bootstrap/bootstrap.js.hbs ), despite that being the failure point. To start up correctly, that application requires `/startup.js` ( source: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/legacy/ui/ui_render/bootstrap/startup.js.hbs )to successfully load and execute first. You can see in the console that `startup.js` failed on an unexpected token on L15: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/legacy/ui/ui_render/bootstrap/startup.js.hbs#L15

That means that there's likely an issue with this block of code:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b5121d37a66f067148056ca9a404634f3a682f94/src/legacy/ui/ui_render/ui_render_mixin.js#L174-L177

which wasn't edited, but moved in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652

**Comment by ananzh** [comment]
@BionIT same question here, is there a way to reproduce locally or could you help to add some repro steps?

**Comment by BionIT** [comment]
To repro: 
- add the commit, see empty page and error in future playground
- remove the commit, OSD bootstraps correctly.

I don't have bandwidth to look further, and I wonder if the change would behave different when it is in container?

**Comment by kavilla** [comment]
looking at the playground. potential cache issue.

i navigated to future.playground after the fix for the key and was able to load fine and was confused. network tab revealed downloaded fresh the startup and bootstrap in that order.

disabled cached. saw it only downloaded bootstrap now.

likely situation @BionIT could it be that you might have navigated to playground and it still cached that startup.js file that had the bug. which then caused the Global Window `_osdThemeTag_` value to be not beproperly set by the startup.js file for then the bootstrap to reference?

**Comment by kavilla** [comment]
reverted in 2.14 in 2.x as @joshuarrrr is addressing existing issue that got exposed by this work but not from this work.

**Comment by BionIT** [comment]
@joshuarrrr Do we still target this fix for 2.15 or 2.16?
