### ISSUE TITLE
[BUG] Data source reference is removed when adding sample data

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6850]
**Describe the bug**

In add sample data page when data source feature is turned on, the data source is added as reference to the index pattern. However, the behavior is lost due to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6105/files#diff-fcdd5446e0a0ea3950cf54e2c6b9fee8011c5429016a8992380c62339e4d051fL63

**To Reproduce**
1. Turn on data source
2. Go to add sample data
3. select a data source from picker.  
4. click on import
5. go to dashboard management, then index pattern, and the data source connection is lost

**Expected behavior**
Data source should be the reference of the index pattern

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by wanglam** [comment]
Hi @BionIT , Thank you for reporting this bug. I think the root cause is removed the data source reference by accident in [this PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6105/files/9a2bd3e198ee040630cf770101a1b5dde89970a1#diff-fcdd5446e0a0ea3950cf54e2c6b9fee8011c5429016a8992380c62339e4d051f). Will add it back and add some unit tests in these codes.
