### ISSUE TITLE
[BUG] Sample visualization based on saved search could not find correct index pattern when added via add sample data page

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6857]
**Describe the bug**
Index pattern id is prefixed with data source id when added via add sample data page, see https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/home/server/services/sample_data/data_sets/util.ts#L70, however, only dashboards' reference is changed to use the new index pattern id, visualization reference is unchanged causing broken visualization with error in finding the index pattern which lacks the prefix

![Screenshot 2024-05-29 at 4 21 45 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/c56d5a08-1ee3-4e2a-9c68-0cfa671e62c4)

**To Reproduce**

**Expected behavior**
Visualization added via add sample data should not break

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
Watch out when addressing this. 

Index pattern ids can be custom as well

**Comment by zhongnansu** [comment]
multiple type of sample visualizations, in different sample data set are not working, create the issue for each of them for tracking, since they each requires different fix
- TSVB:  https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6936
- Vis builder: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6938
- regular visualizations only fails in `Visual Consistency Dashboard`
