### ISSUE TITLE
[MDS] UI polishment for MDS support of Timeline visualization 

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#7000]
Tasks
- [ ] Polish error message to be `data_source_name is not supported. Contact your administrator to start using multiple data sources` when data source feature is not enabled
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/5aafcafb-0cae-4b4f-ba35-a2136e5fa5b8)
Link PR: 

2. Place data source name before the index name in the expression. Hierarchically user selects data source first, then index name, then metric and timestamp

- [ ] Add data source helper text into the help tooltip
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/c713b1bb-e16f-498b-a3e7-5091670bd695)

**Comment by zhongnansu** [comment]
- For task 1: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7069
- For task 2: "place data source name before the index name". Based on @huyaboo, is not doable. Could you add more context?
- For task 3,  I found that there's already helper text added in the helper tool tip. See below screenshot
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/fc1f2286-1289-4eb0-bf88-f239d3e9e4bb)

cc: @xeniatup @BionIT

**Comment by xeniatup** [comment]
`For task 2: "place data source name before the index name". Based on @huyaboo, is not doable. Could you add more context?`
I would not consider it a blocker. The suggestion was based on the general hierarchy of the objects (data source contains multiple indexes, an index has metric, etc..)

**Comment by huyaboo** [comment]
> For task 2: "place data source name before the index name". Based on @huyaboo, is not doable. Could you add more context?

If a specific Timeline visualization does not use named arguments, the arguments are assigned to named arguments in a specific order: `queries, metric, split, index, ...`

In other words `data_source_name` were placed first or in the middle, it would break existing Timeline visualizations because the argument order would be modified. This is why `data_source_name` is placed last.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/7aa61e42bf362156e9d2feaba1a4f5ec069dccaf/src/plugins/vis_type_timeline/server/series_functions/opensearch/index.js#L40C1-L124C5
