### ISSUE TITLE
[Build] Upgrade Node.js from v10 to v12

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#716]
Subtask of: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/406

We're currently running Node.js v10.24.1. This sub-issue will track progress towards upgrading to at least v12 on our road to v16. That way if we have a dependency and that requires at least Node.js 12 then we can track it better. Also, the change from v10 to v16 might be large so it breaks it into chunks.

**Comment by MerwaneHAMADI** [comment]
This would be great, there are some functionalities in my code editor I don't get because node is too old.

I have a question : why are we in version 10 ? Kibana upgraded to v12 before the fork : 
https://github.com/elastic/kibana/commits/master/.nvmrc
By the way, [this](https://github.com/elastic/kibana/commit/4c49d5d1be0b959be515307131c1a420226c372b#diff-2c8effdf840690ccb88c7e21e56148978c6adb2c6926530c58ff0e47a9588b44) is probably what needs to be changed if we bump the version.

**Comment by boktorbb-amzn** [comment]
Closing this issue in favor of a plan to move directly to Node 16 outlined in the parent issue #406
