### ISSUE TITLE
[Enhancement] Compatibility check prevents Elasticsearch backend

### ISSUE THREAD

**Issue by drewrutl** [opensearch-project/OpenSearch-Dashboards#720]
**Describe the bug**

It's probably not an intended use case, but it seems like compatibility checks comparing Elasticsearch/Kibana versions (and Opensearch/OS-Dashboards) prevent the use of Elasticsearch with Opensearch-Dashboards. I was attempting to use an existing Amazon Elasticsearch Service cluster as the backend for an on-prem Opensearch Dashboard, trying to follow the instructions for connecting a local Kibana instance to Amazon ES found here: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-kibana.html#es-kibana-local

However, when attempting to start the dashboard service with this set as the backend in the config file, I received this error:
`[error][savedobjects-service] This version of OpenSearch Dashboards (v1.0.0) is incompatible with the following OpenSearch nodes in your cluster: v7.10.2 @ undefined (undefined)`

I assume this could be related to the old version compatibility matrix for ES/Kibana where major version differences are incompatible - https://github.com/elastic/kibana#version-compatibility-with-elasticsearch

**To Reproduce**
Configure the backend for Opensearch Dashboards to point to any Amazon ES instance or Elasticsearch instance using Elastic's versioning scheme

**Expected behavior**
If this is at all considered a supported configuration, logic to differentiate between Elasticsearch and OpenSearch version numbers, or a flag to ignore compatibility checks, should allow this to work.

**OpenSearch Version**
Elasticsearch 7.10.2 (Amazon ES)

**Dashboards Version**
1.0.0

**Plugins**

N/A

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2

**Comment by kavilla** [comment]
Hey @drewrutl!

Yeah there is logic to prevent major version differences because the data might have changed and this could create corrupted data. But for OSD 1.0.0 we specifically reverted any data changes so technically it should work with OS 1.0.0 or ES 7.10.2

My proposal is that if and only if OSD is 1.0.0 and the engines are on version 7.10.2 or 1.0.0 then the application can start. We shouldn't consider making it supported configuration to prevent any future corruptions in data if we do end up planning on changing the data.

What do people think?

**Comment by dblock** [comment]
> What do people think?

If we can make sure integration tests run on such a configuration, why not.

**Comment by kavilla** [comment]
Updated to make it an enhancement.
