### ISSUE TITLE
Easy way to replace OpenSearch Dashboards "logo"

### ISSUE THREAD

**Issue by bluepeter** [opensearch-project/OpenSearch-Dashboards#798]
Searching around, there are various complex ways to update the OS logo that lives in the top-left. It would be super if there was a way to easily update the logo and other design elements in `Stack Management > Advanced Settings` (this would also allow us to update the logo as part of AWS OpenSearch Service).

Messing around with the logo is explicitly against Elastic's TOS, so we appreciate the flexibility we have with OSD to allow for this customization. However, there's not an easy or straightforward way to do this?

**Comment by ahopp** [comment]
I think this is related  to this proposal: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/725

@bluepeter Can you take a look and see if that covers you ask?

**Comment by bluepeter** [comment]
Thank you @ahopp for that reference. This would mostly solve our issue. However, instead of relying on a separate `.yaml` file, we'd love an easy way to adjust the logo (and/or insert custom CSS/JS) from the OS Dashboards interface itself. This would then allow us to still use AWS OpenSearch Service, versus having to deploy the solution via container to support a separate file (which I don't believe is possible via AWS OS).

**Comment by abbyhu2000** [comment]
@bluepeter Thank you for your feedback! Currently making branding configuration into OSD interface/Advanced settings will need more time and consideration because of the implications with other plugins.

For example, if user installs security plugin, user will be able to switch among different tenants. However, the advanced setting is saved using the .kibana index and each tenant has its own unique .kibana index. Therefore, if user sets the advanced setting in one tenant, only that tenant will render that specific branding customization. When user switch out to another tenant, user will see a different dashboard UI if the branding configuration in that tenant are set differently. We are currently not sure if we wish this type of user experience so we are holding off on incorporating branding configurations under Advances Settings.

Therefore, yaml file will be the starting point and foundation for a more user-friendly branding customization solution in the future.

**Comment by bluepeter** [comment]
@abbyhu2000 makes sense. Closing for now.
