### ISSUE TITLE
[BUG] New default maps service cached policy causing CORS issue

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#963]
**Describe the bug**

We navigating to a new maps services `maps.opensearch.org`. Went trying to use it out of the box I keep getting a CORS issue when trying to access a visualization with maps. I had to manually clear my cache then I was able to see maps out of the box. It could potentially be we got some policy cached for the old service and when it attempts to make a call it is making a call with the old policy causing a CORS issue.

**To Reproduce**
1. Have old service working
2. Create a viz with region maps
3. Notice map
4. Use new map service
5. Create a viz with region maps
6. Notice CORS issue

**Expected behavior**
Maps works out of the box

**OpenSearch Version**
1.2

**Dashboards Version**
1.2

**Plugins**
n/a

**Screenshots**
n/a

**Additional context**

Need to verify if other folks are seeing this. And will add more content to this issue once I recreate it.

**Comment by AMoo-Miki** [comment]
Looking at the headers of the failure, we found that CORS headers we missing in the response from the CDN. That is even though the CDN was configured to respond with CORS headers and had been working find.

One theory is that the failing file, `v2.json`, was requested in a non-XHR context and a CDN edge cached the response without the CORS headers. Subsequently, a request for the same file, when made via `fetch`, received the cached response from the CDN which didn't contain the CORS headers.

Will continue to look for other explanations with refreshing the CDN cache.

**Comment by AMoo-Miki** [comment]
The scenario described earlier was reproducible all the time and from what I gather is due to the way headers sent from our origin storage are cached at the CDN. When a request for an asset is made without an `Origin` header, typical of non-XHR requests, the origin returns no CORS headers and the asset gets cached without headers on the CDN. For the next fixed amount of time (TTL), the CDN would serve all requests for that asset with the cached version that has no CORS headers, even if a request lands with the `Origin` header.

The best solution would have been to be able to instruct the CDN to differentiate cached assets based on the existence of an `Origin` header on the request; currently we don't care for its value as we allow access to all origins. Sadly this is not possible and that leaves us with 2 options:
* Overwrite all incoming requests to add an `Origin` header to force our origin to serve the CORS headers. 
* Add CORS headers to all outgoing responses.

With adding the `Origin` header, we would be dependent on a current behavior of the origin which is beyond our control; this puts us at risk if it changes. Hence, I chose to implement the latter which is really harmless except for the 100 or so bytes of excess header that it will impose on all non-XHR assets but considering all the unnecessary data we are already sending in headers, this is minor cost.

**Comment by kavilla** [comment]
Thanks @AMoo-Miki for the assistance!

**Comment by dblock** [comment]
@kavilla What was the fix?

**Comment by AMoo-Miki** [comment]
> @kavilla @AMoo-Miki What was the fix? Is it OSS (is there a PR?)

We just instructed the CDN to add CORS headers on all responses that missing them. No code change.

**Comment by dblock** [comment]
@tmarkley @kavilla I understand we changed something in a live configuration. That's ok as an immediate workaround, but it's not a fix. I'll reopen until we confirm that the change made it into code (CDK or otherwise).

**Comment by junqiuamz** [comment]
We have a proprietary CDK pipeline for the maps service. A permanent fix was made in CDK pipeline and deployed.

**Comment by cwegener** [comment]
Hi @AMoo-Miki 

Thanks for this good write up. Very interesting.

Out of curiosity, one question related to the new Maps service:
Was there a deliberate decision to **not** allow Preflight request for the Opensearch Maps service?

Mainly asking because Elastic seem to go the other route and they **do** allow Preflight requests.
